let save=Store.load(),match=null,tour=save.tour||null,pendingTournamentOpponent=null,selectedStarter=null;
const diffNames={easy:'轻松',normal:'标准',hard:'专家'};
function persist(){save.tour=tour;Store.save(save);$('#coins').textContent=save.coins||0;$('#wins').textContent=save.wins||0}
function switchTab(id){$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===id))}
function init(){['quickA','quickB','tourTeam','manageTeam','coachTeam'].forEach(id=>Render.teamOptions($('#'+id)));Render.teamOptions($('#filterTeam'));$('#quickA').value='西班牙';$('#quickB').value='阿根廷';$('#tourTeam').value='西班牙';$('#manageTeam').value='西班牙';$$('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#startQuick').onclick=startQuick;$('#goQuick').onclick=()=>{switchTab('home');startQuick()};$('#goTour').onclick=()=>switchTab('tour');$('#nextRound').onclick=prepareRound;$('#autoFinish').onclick=autoFinish;$('#resetMatch').onclick=()=>{match=null;switchTab('home')};$('#quickA').onchange=renderHome;$('#quickB').onchange=renderHome;$('#manageTeam').onchange=renderSquadManager;$('#manageFormation').onchange=changeFormation;$('#captainSelect').onchange=()=>{Lineup.get($('#manageTeam').value,save).captainId=$('#captainSelect').value;persist();renderSquadManager()};$('#setPieceSelect').onchange=()=>{Lineup.get($('#manageTeam').value,save).setPieceId=$('#setPieceSelect').value;persist()};$('#filterTeam').onchange=renderPlayers;$('#detailOnly').onchange=renderPlayers;$('#startTour').onclick=startTour;$('#tourNext').onclick=tourNext;$('#resumeTour').onclick=()=>{renderTournament();switchTab('tour')};$('#wipeSave').onclick=wipeSave;$('#runSimulation').onclick=runSimulation;$('#runMatrix').onclick=runMatrix;$('#refreshDashboard').onclick=renderDashboard;$('#generateCoach').onclick=generateCoach;$('#openSub').onclick=openSubModal;$('#closeSub').onclick=()=>$('#subModal').classList.remove('show');$('#closeModal').onclick=()=>$('#modal').classList.remove('show');$('#welcomeClose').onclick=()=>{$('#welcome').classList.remove('show');save.versionSeen='1.2';persist()};if(save.versionSeen!=='1.2')setTimeout(()=>$('#welcome').classList.add('show'),300);renderAll();persist()}
function renderAll(){renderHome();renderSquadManager();renderPlayers();renderTrain();renderTourPreview();renderTournament();renderTech();renderDashboard()}
function summary(t){let m=TEAM_META[t]||{},l=Lineup.get(t,save);return `${m.style||'均衡'} · ${l.formation} · 强度${Growth.strengthOf(t)} · ${PLAYER_DATA[t]?'精细卡组':'模拟卡组'}`}
function renderHome(){let a=$('#quickA').value,b=$('#quickB').value;$('#quickASummary').textContent=summary(a);$('#quickBSummary').textContent=summary(b);$('#squadGrid').innerHTML=Lineup.players(a,save).map(p=>Render.playerCard(p,`onclick="showPlayer('${Render.esc(p.id)}')"`)).join('')}
function renderSquadManager(){let t=$('#manageTeam').value,l=Lineup.get(t,save);$('#manageFormation').innerHTML=Object.keys(Lineup.formations).map(x=>`<option ${x===l.formation?'selected':''}>${x}</option>`).join('');let all=Growth.roster(t,save,true);$('#captainSelect').innerHTML=all.map(p=>`<option value="${p.id}" ${p.id===l.captainId?'selected':''}>${p.name}</option>`).join('');$('#setPieceSelect').innerHTML=all.map(p=>`<option value="${p.id}" ${p.id===l.setPieceId?'selected':''}>${p.name}</option>`).join('');$('#formationDescription').textContent=Lineup.formations[l.formation].desc;$('#starterList').innerHTML=Lineup.players(t,save,'starters').map(p=>lineupRow(p,true)).join('');$('#benchList').innerHTML=Lineup.players(t,save,'bench').map(p=>lineupRow(p,false)).join('');let active=COMBOS.filter(c=>!c.team||c.team===t).slice(0,8);$('#comboPreview').innerHTML=active.map(c=>`<div class="combo-chip"><b>${c.name}</b><span>${c.text}</span></div>`).join('')||'<p class="small">暂无专属连携。</p>'}
function lineupRow(p,isStarter){return `<button class="lineup-row ${selectedStarter===p.id?'selected':''}" onclick="${isStarter?`selectStarter('${Render.esc(p.id)}')`:`swapBench('${Render.esc(p.id)}')`}"><span>${p.pos}</span><b>${p.name}</b><em>${Growth.overall(p)}</em></button>`}
function selectStarter(id){selectedStarter=selectedStarter===id?null:id;renderSquadManager()}
function swapBench(id){if(!selectedStarter)return Render.modal('提示','<p>请先点击一名首发球员，再点击替补完成互换。</p>');Lineup.swap($('#manageTeam').value,save,selectedStarter,id);selectedStarter=null;persist();renderSquadManager();renderHome()}
function changeFormation(){Lineup.setFormation($('#manageTeam').value,save,$('#manageFormation').value);persist();renderSquadManager()}
function startQuick(){let a=$('#quickA').value,b=$('#quickB').value;if(a===b)return alert('请选择不同球队');match=MatchEngine.newState(a,b,save,{mode:'快速比赛',difficulty:$('#difficulty').value});switchTab('match');resetMatchView();updateScore();addLog(`比赛开始：${a} 对阵 ${b}。`)}
function resetMatchView(){$('#matchLog').innerHTML='';$('#duelA').textContent='等待牌阵';$('#duelB').textContent='等待牌阵';$('#sceneInfo').textContent='点击“生成下一回合”。';$('#tacticPanel').classList.add('hidden');$('#probExplain').innerHTML='<b>概率解释：</b>等待结算。'}
function prepareRound(){if(!match)return startQuick();if(match.round>=match.maxRounds)return finishMatch();let p=MatchEngine.preview(match);$('#sceneInfo').innerHTML=`<b>${p.minute}' · ${p.scene.name}</b><br><span class="small">${p.scene.desc} · ${p.atk}进攻</span>`;$('#duelA').innerHTML=Render.miniBattleCards(p.atk===match.teamA?p.atkCards:p.defCards);$('#duelB').innerHTML=Render.miniBattleCards(p.atk===match.teamB?p.atkCards:p.defCards);$('#tacticPanel').classList.remove('hidden');$('#tacticChoices').innerHTML=Object.entries(MatchEngine.tactics).map(([k,t])=>`<button onclick="chooseTactic('${k}')"><b>${t.name}</b><span>${t.desc}</span></button>`).join('')}
function chooseTactic(k){if(!match||!match.pending)return;let r=MatchEngine.resolve(match,k);$('#tacticPanel').classList.add('hidden');renderRound(r);if(match.round>=match.maxRounds)setTimeout(finishMatch,250)}
function renderRound(r){let leftAtk=r.atk===match.teamA;$('#duelA').innerHTML=`<div class="side-title">${match.teamA} · ${leftAtk?'进攻':'防守'} · ${Math.round(leftAtk?r.atk.value:r.def.value)}</div>${Render.miniBattleCards(leftAtk?r.atkCards:r.defCards)}`;$('#duelB').innerHTML=`<div class="side-title">${match.teamB} · ${!leftAtk?'进攻':'防守'} · ${Math.round(!leftAtk?r.atk.value:r.def.value)}</div>${Render.miniBattleCards(!leftAtk?r.atkCards:r.defCards)}`;let event=r.goal?`⚽ ${r.scorer.name}进球！`:r.counter?`⚡ 反击得分：${r.scorer.name}`:r.shot?`🧤 门将化解射门`:`⛔ 未形成射门`;$('#probExplain').innerHTML=`<b>为什么：</b>${r.explain.map(x=>`<span>${x}</span>`).join('')}<strong>形成射门 ${(r.shotProb*100).toFixed(1)}%</strong>`;addLog(`${r.minute}' ${r.scene.name}｜${r.tactic.name}｜${event}`);updateScore()}
function addLog(s){$('#matchLog').insertAdjacentHTML('afterbegin',`<div>${s}</div>`)}
function updateScore(){if(!match)return;$('#scoreNameA').textContent=match.teamA;$('#scoreNameB').textContent=match.teamB;$('#scoreA').textContent=match.scoreA;$('#scoreB').textContent=match.scoreB;$('#round').textContent=match.round;$('#maxRound').textContent=match.maxRounds;$('#minute').textContent=(match.minute||0)+"'";$('#moraleA').textContent=Math.round(match.moraleA);$('#moraleB').textContent=Math.round(match.moraleB);$('#matchMode').textContent=match.mode;$('#matchDifficulty').textContent=diffNames[match.difficulty];$('#fitnessA').innerHTML=fitnessSummary(match.teamA);$('#fitnessB').innerHTML=fitnessSummary(match.teamB)}
function fitnessSummary(team){let ps=Lineup.players(team,save),avg=ps.reduce((s,p)=>s+(match.fitness[p.id]||100),0)/ps.length;return `<span>${team}体能 ${Math.round(avg)}%</span><i style="width:${avg}%"></i>`}
function autoFinish(){if(!match)return startQuick();while(match.round<match.maxRounds){if(!match.pending)MatchEngine.preview(match);let r=MatchEngine.resolve(match,'control');renderRound(r)}finishMatch()}
function finishMatch(){if(!match||match.finished)return;match.finished=true;if(match.knockout&&match.scoreA===match.scoreB){let p=MatchEngine.penalties(match.teamA,match.teamB);p.winner===match.teamA?match.scoreA++:match.scoreB++;addLog(`点球大战：${p.winner}晋级`)}let res=match.scoreA>match.scoreB?'win':match.scoreA===match.scoreB?'draw':'loss',award=Growth.award(match.teamA,save,res,Object.keys(match.fitness).filter(id=>match.fitness[id]<100)),total=match.stats.possessionA+match.stats.possessionB||1,body=`<div class="statline"><div class="mini">比分<br><b>${match.scoreA}:${match.scoreB}</b></div><div class="mini">射门<br><b>${match.stats.shotsA}:${match.stats.shotsB}</b></div><div class="mini">射正<br><b>${match.stats.onA}:${match.stats.onB}</b></div><div class="mini">控球<br><b>${Math.round(match.stats.possessionA/total*100)}%</b></div></div><p>金币 +${award.coins}，基础经验 +${award.xp}。成长已继承到下一场。</p>`;Analytics.record(save,match,'control');save.history.unshift({date:new Date().toISOString(),a:match.teamA,b:match.teamB,score:`${match.scoreA}:${match.scoreB}`});save.history=save.history.slice(0,30);persist();Render.modal(res==='win'?'🏆 比赛胜利':res==='draw'?'🤝 平局':'比赛结束',body);if(match.mode==='tour-group')afterTourGroupMatch();if(match.mode==='tour-ko')afterTourKoMatch();renderTrain()}
function openSubModal(){if(!match)return;let team=match.teamA,st=Lineup.players(team,save,'starters'),be=Lineup.players(team,save,'bench');$('#subBody').innerHTML=`<p class="small">已换 ${match.subsA}/5 人。先选择下场球员，再选择替补。</p><select id="subOut">${st.map(p=>`<option value="${p.id}">${p.name} 体能${Math.round(match.fitness[p.id]||100)}%</option>`).join('')}</select><select id="subIn">${be.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select><button class="btn primary full" onclick="confirmSub()">确认换人</button>`;$('#subModal').classList.add('show')}
function confirmSub(){let ok=MatchEngine.substitute(match,match.teamA,$('#subOut').value,$('#subIn').value);if(ok){persist();$('#subModal').classList.remove('show');addLog('🔄 完成换人，新球员体能100%。');updateScore()}else alert('换人失败或已达到5人上限')}
function showPlayer(id){let p=null;Object.values(PLAYER_DATA).forEach((arr)=>{let t=arr.find(x=>id.endsWith('|'+x[0]));if(t){let team=id.split('|')[0];p=Growth.roster(team,save,true).find(x=>x.id===id)}});if(!p){for(let t of Object.values(WORLD_CUP_GROUPS).flat()){p=Growth.roster(t,save,true).find(x=>x.id===id);if(p)break}}if(!p)return;Render.drawRadar(p);$('#playerDetail').innerHTML=`<h2>${p.name} <span class="stage-badge">${Growth.overall(p)}</span></h2><p>${p.team} · ${p.pos} · Lv.${p.level}</p><div class="skills">${(p.skills||[]).map(s=>`<span class="skill">✦ ${s}</span>`).join('')||'团队球员'}</div><p class="small">技能为条件触发：相关场景、关键时间、能力与随机检定共同决定，并受单回合技能加成上限约束。</p>`}
function renderPlayers(){let team=$('#filterTeam').value,teams=$('#detailOnly').checked?Object.keys(PLAYER_DATA):Object.values(WORLD_CUP_GROUPS).flat(),arr=(team&&teams.includes(team)?Growth.roster(team,save,true):teams.flatMap(t=>Growth.roster(t,save,true))).slice(0,220);$('#playerCount').textContent=arr.length;$('#playerGrid').innerHTML=arr.map(p=>Render.playerCard(p,`onclick="showPlayer('${Render.esc(p.id)}')"`)).join('')}
function renderTrain(){let t=$('#quickA').value||'西班牙';$('#upgradeGrid').innerHTML=Growth.roster(t,save,true).slice(0,16).map(p=>`${Render.playerCard(p)}<button class="btn full" onclick="trainPlayer('${Render.esc(p.id)}')">定向训练 120金币</button>`).join('')}
function trainPlayer(id){let r=Growth.train(id,save,$('#trainFocus').value);if(!r.ok)return alert(r.msg);persist();renderTrain();renderHome();Render.modal('训练完成',`<p>${r.stat}获得提升，球员经验增加。</p>`)}
function wipeSave(){if(confirm('确定清除全部存档？')){Store.wipe();location.reload()}}
function renderTourPreview(){let t=$('#tourTeam').value,g=Object.entries(WORLD_CUP_GROUPS).find(([_,a])=>a.includes(t));$('#tourPreview').innerHTML=g?`<p>${g[0]}组：${g[1].join('、')}</p>`:''}
function startTour(){tour=Tournament.start($('#tourTeam').value);save.tour=tour;persist();renderTournament();Render.modal('世界杯征途已创建',`<p>${tour.team}将从${tour.group}组开始。</p>`)}
function renderTournament(){if(!tour){$('#tourState').innerHTML='<div class="notice">尚未开启征途。</div>';return}let rows=Tournament.groupRows(tour,tour.group),next=tour.matchIndex<tour.opponents.length?tour.opponents[tour.matchIndex]:Tournament.nextOpponent(tour);$('#tourState').innerHTML=`<div class="box"><h2>${tour.team} · ${tour.stage}</h2>${Render.tableHtml(rows)}<p>下一场：${tour.eliminated?'已出局':tour.champion?'已夺冠':next||'等待赛程'}</p></div>`}
function tourNext(){if(!tour)return startTour();if(tour.eliminated||tour.champion)return;let opp=!tour.groupDone?tour.opponents[tour.matchIndex]:Tournament.nextOpponent(tour);match=MatchEngine.newState(tour.team,opp,save,{mode:tour.groupDone?'tour-ko':'tour-group',knockout:tour.groupDone,difficulty:'normal'});pendingTournamentOpponent=opp;switchTab('match');resetMatchView();updateScore();addLog(`世界杯征途：${tour.team} 对阵 ${opp}`)}
function afterTourGroupMatch(){Tournament.recordUserGroup(tour,pendingTournamentOpponent,match.scoreA,match.scoreB);persist();renderTournament()}
function afterTourKoMatch(){Tournament.recordKnockout(tour,pendingTournamentOpponent,match.scoreA>match.scoreB,`${match.scoreA}:${match.scoreB}`);persist();renderTournament()}
function runSimulation(){let n=Number($('#simCount').value),r=Simulation.run(n);$('#simulationResult').innerHTML=`<h2>${n}场模拟结果</h2><div class="statline"><div class="mini">场均进球<br><b>${r.avg}</b></div><div class="mini">平局率<br><b>${r.draw}%</b></div><div class="mini">较强队胜率<br><b>${r.strong}%</b></div><div class="mini">明显爆冷率<br><b>${r.upset}%</b></div></div><p>高频比分：${r.top.map(x=>`${x[0]}（${x[1]}）`).join('、')}</p><p class="small">该结果用于初步平衡观察，不等同于真实世界杯预测。</p>`}
function renderTech(){$('#techStatus').innerHTML=`<p>存档结构版本：${save.schemaVersion}</p><p>随机种子：比赛内可复现式生成</p><p>阵容数据：与比赛引擎分离</p><p>赛事、成长、UI：独立模块</p><p>已知限制：尚未完成真实外部玩家测试与全设备兼容验证。</p>`}
window.showPlayer=showPlayer;window.trainPlayer=trainPlayer;window.selectStarter=selectStarter;window.swapBench=swapBench;window.chooseTactic=chooseTactic;window.confirmSub=confirmSub;
window.addEventListener('load',init);
function renderDashboard(){let s=Analytics.summary(save);$('#dashboardCards').innerHTML=`<div class="mini">比赛<br><b>${s.matches}</b></div><div class="mini">胜率<br><b>${s.winRate}%</b></div><div class="mini">场均进球<br><b>${s.avgFor}</b></div><div class="mini">场均失球<br><b>${s.avgAgainst}</b></div><div class="mini">常用阵型<br><b>${s.topFormation}</b></div>`;$('#recentMatches').innerHTML=(save.history||[]).slice(0,8).map(x=>`<p>${new Date(x.date).toLocaleDateString()} · ${x.a} ${x.score} ${x.b}</p>`).join('')||'<p class="small">暂无比赛记录。</p>';$('#sprintStatus').innerHTML='<p>✅ Schema 13存档迁移</p><p>✅ 数据驾驶舱基础</p><p>✅ AI教练规则框架</p><p>✅ 阵型/战术矩阵模拟</p><p>⏳ 每日任务、经济系统、模拟商城：Sprint 2</p>'}
function generateCoach(){let r=CoachEngine.report(save,$('#coachTeam').value);save.coachReports.unshift(r);save.coachReports=save.coachReports.slice(0,10);persist();$('#coachReport').innerHTML=`<h2>${r.team}教练报告</h2><p>当前阵型：${r.formation}｜样本：${r.summary.matches}场｜胜率：${r.summary.winRate}%</p>${r.advice.map(x=>`<div class="notice compact">${x}</div>`).join('')}`}
function runMatrix(){let n=Number($('#matrixCount').value),r=AdvancedSimulation.run({perPair:n});window.lastMatrix=r;let f=AdvancedSimulation.formations,t=AdvancedSimulation.tactics;function table(labels,data,names){return `<table><tr><th>进攻方\\防守方</th>${labels.map(x=>`<th>${names?.[x]||x}</th>`).join('')}</tr>${labels.map(a=>`<tr><th>${names?.[a]||a}</th>${labels.map(b=>`<td>${data[a][b].win}%</td>`).join('')}</tr>`).join('')}</table>`}$('#matrixResult').innerHTML=`<h3>阵型胜率矩阵</h3>${table(f,r.formations)}<h3>战术胜率矩阵</h3>${table(t,r.tactics,r.tacticNames)}<p class="small">每个格子模拟${n}场，仅用于Sprint 1技术验证。</p>`}
