let save=Store.load(),match=null,tour=save.tour||null,pendingTournamentOpponent=null,selectedStarter=null;
const diffNames={easy:'轻松',normal:'标准',hard:'专家'};
function persist(){save.tour=tour;save.activeMatch=match&&!match.finished?JSON.parse(JSON.stringify(match)):null;Store.save(save);$('#coins').textContent=save.coins||0;$('#wins').textContent=save.wins||0;updateRecoveryUI()}
function switchTab(id){dismissMatchEvent();$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===id));save.lastTab=id;try{Store.save(save)}catch(_){}}
function init(){['quickA','quickB','tourTeam','manageTeam','coachTeam'].forEach(id=>Render.teamOptions($('#'+id)));Render.teamOptions($('#filterTeam'));$('#quickA').value='西班牙';$('#quickB').value='阿根廷';$('#tourTeam').value='西班牙';$('#manageTeam').value='西班牙';$$('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#startQuick').onclick=startQuick;$('#goQuick').onclick=()=>{switchTab('home');startQuick()};$('#goTour').onclick=()=>switchTab('tour');bindMatchControls();$('#resetMatch').onclick=exitCurrentMatch;$('#quickA').onchange=renderHome;$('#quickB').onchange=renderHome;$('#manageTeam').onchange=renderSquadManager;$('#manageFormation').onchange=changeFormation;$('#captainSelect').onchange=()=>{Lineup.get($('#manageTeam').value,save).captainId=$('#captainSelect').value;persist();renderSquadManager()};$('#setPieceSelect').onchange=()=>{Lineup.get($('#manageTeam').value,save).setPieceId=$('#setPieceSelect').value;persist()};$('#filterTeam').onchange=renderPlayers;$('#detailOnly').onchange=renderPlayers;$('#startTour').onclick=startTour;const ctl=$('#counterLabToggle');if(ctl)ctl.onchange=()=>{if(match){match.experiments=match.experiments||{};match.experiments.counterChain=ctl.checked;persist()}};$('#tourNext').onclick=tourNext;$('#resumeTour').onclick=()=>{renderTournament();switchTab('tour')};$('#wipeSave').onclick=wipeSave;$('#runSimulation').onclick=runSimulation;$('#runMatrix').onclick=runMatrix;$('#saveFeedback').onclick=saveFeedback;$('#exportJson').onclick=()=>ReportExporter.json(save);$('#exportCsv').onclick=()=>ReportExporter.csv(save);$('#copyFeedback').onclick=copyFeedback;$('#refreshDashboard').onclick=renderDashboard;$('#generateCoach').onclick=generateCoach;$('#openSub').onclick=openSubModal;$('#closeSub').onclick=()=>$('#subModal').classList.remove('show');$('#closeModal').onclick=()=>{const m=$('#modal');m.classList.remove('show');if(postMatchReturnTarget==='tour'){postMatchReturnTarget=null;renderTournament();switchTab('tour')}};$('#welcomeClose').onclick=()=>{$('#welcome').classList.remove('show');save.versionSeen='1.8-a2';persist()};if(save.versionSeen!=='1.8-a2')setTimeout(()=>$('#welcome').classList.add('show'),300);renderAll();restoreActiveMatch();initV14UX();persist()}
function renderAll(){renderHome();renderSquadManager();renderPlayers();renderTrain();renderTourPreview();renderTournament();renderTech();renderDashboard()}
function exitCurrentMatch(){dismissMatchEvent();const mode=match&&match.mode;const fromTournament=mode==='tour-group'||mode==='tour-ko';if(match&&!match.finished&&!confirm(fromTournament?'本场尚未结束，确定退出本场并返回世界杯征程吗？本场恢复点将被清除。':'本场尚未结束，确定退出并清除本场恢复点吗？'))return;match=null;save.activeMatch=null;setMatchPhase('idle');const modal=$('#modal');if(modal)modal.classList.remove('show');persist();if(fromTournament){renderTournament();switchTab('tour')}else switchTab('home')}
function summary(t){let m=TEAM_META[t]||{},l=Lineup.get(t,save);return `${m.style||'均衡'} · ${l.formation} · 强度${Growth.strengthOf(t)} · ${PLAYER_DATA[t]?'精细卡组':'模拟卡组'}`}
function renderHome(){let a=$('#quickA').value,b=$('#quickB').value;$('#quickASummary').textContent=summary(a);$('#quickBSummary').textContent=summary(b);$('#squadGrid').innerHTML=Lineup.players(a,save).map(p=>Render.playerCard(p,`onclick="showPlayer('${Render.esc(p.id)}')"`)).join('')}
function renderSquadManager(){let t=$('#manageTeam').value,l=Lineup.get(t,save);$('#manageFormation').innerHTML=Object.keys(Lineup.formations).map(x=>`<option ${x===l.formation?'selected':''}>${x}</option>`).join('');let all=Growth.roster(t,save,true);$('#captainSelect').innerHTML=all.map(p=>`<option value="${p.id}" ${p.id===l.captainId?'selected':''}>${p.name}</option>`).join('');$('#setPieceSelect').innerHTML=all.map(p=>`<option value="${p.id}" ${p.id===l.setPieceId?'selected':''}>${p.name}</option>`).join('');$('#formationDescription').textContent=Lineup.formations[l.formation].desc;$('#starterList').innerHTML=Lineup.players(t,save,'starters').map(p=>lineupRow(p,true)).join('');$('#benchList').innerHTML=Lineup.players(t,save,'bench').map(p=>lineupRow(p,false)).join('');let active=COMBOS.filter(c=>!c.team||c.team===t).slice(0,8);$('#comboPreview').innerHTML=active.map(c=>`<div class="combo-chip"><b>${c.name}</b><span>${c.text}</span></div>`).join('')||'<p class="small">暂无专属连携。</p>'}
function lineupRow(p,isStarter){return `<button class="lineup-row ${selectedStarter===p.id?'selected':''}" onclick="${isStarter?`selectStarter('${Render.esc(p.id)}')`:`swapBench('${Render.esc(p.id)}')`}"><span>${p.pos}</span><b>${p.name}</b><em>${Growth.overall(p)}</em></button>`}
function selectStarter(id){selectedStarter=selectedStarter===id?null:id;renderSquadManager()}
function swapBench(id){if(!selectedStarter)return Render.modal('提示','<p>请先点击一名首发球员，再点击替补完成互换。</p>');Lineup.swap($('#manageTeam').value,save,selectedStarter,id);selectedStarter=null;persist();renderSquadManager();renderHome()}
function changeFormation(){Lineup.setFormation($('#manageTeam').value,save,$('#manageFormation').value);persist();renderSquadManager()}
function startQuick(){BetaTools.log(save,'match-start',{mode:'quick',group:BetaRelease.config.testerGroup});let a=$('#quickA').value,b=$('#quickB').value;if(a===b)return alert('请选择不同球队');match=MatchEngine.newState(a,b,save,{mode:'快速比赛',difficulty:$('#difficulty').value});setMatchPhase('ready');switchTab('match');resetMatchView();updateScore();addLog(`比赛开始：${a} 对阵 ${b}。`);persist()}
function resetMatchView(){setMatchPhase(match?'ready':'idle');const ctl=$('#counterLabToggle');if(ctl)ctl.checked=!!(match&&match.experiments&&match.experiments.counterChain);$('#matchLog').innerHTML='';$('#duelA').textContent='等待牌阵';$('#duelB').textContent='等待牌阵';$('#sceneInfo').textContent='点击“生成下一回合”。';$('#tacticPanel').classList.add('hidden');$('#probExplain').innerHTML='<b>概率解释：</b>等待结算。';if(window.V18Experience)V18Experience.resetUI(match)}
let roundActionBusy=false;
function bindMatchControls(){
 const next=$('#nextRound'),auto=$('#autoFinish');
 if(next){next.type='button';next.onclick=null;next.addEventListener('click',safePrepareRound,{passive:false});next.addEventListener('touchend',safeTouchPrepare,{passive:false});}
 if(auto){auto.type='button';auto.onclick=autoFinish;}
}
function safeTouchPrepare(e){e.preventDefault();safePrepareRound(e)}
function setRoundButtonState(busy,text){const b=$('#nextRound');if(!b)return;b.disabled=!!busy;b.textContent=text||(busy?'正在生成…':'生成下一回合');b.setAttribute('aria-busy',busy?'true':'false')}
function showRoundError(err){setMatchPhase('error');console.error('NEXT_ROUND_FAILED',err);setRoundButtonState(false,'重试生成下一回合');$('#sceneInfo').innerHTML='<b>本回合生成失败</b><br><span class="small">已记录错误，请点击重试；若仍失败，请在封测中心提交Bug。</span>';addLog('⚠️ 回合生成失败：'+(err&&err.message?err.message:'未知错误'));try{BetaTools.log(save,'next-round-error',{message:String(err&&err.message||err),stack:String(err&&err.stack||'')});persist()}catch(_){}}
function safePrepareRound(e){dismissMatchEvent();if(e&&e.preventDefault)e.preventDefault();if(roundActionBusy)return;roundActionBusy=true;setMatchPhase('generating');setRoundButtonState(true);requestAnimationFrame(()=>{try{prepareRound();setRoundButtonState(false,match&&match.pending?'请选择战术':'生成下一回合')}catch(err){showRoundError(err)}finally{roundActionBusy=false}})}
function prepareRound(){
 if(!match){startQuick();if(!match)throw new Error('比赛状态未成功创建');}
 if(match.round>=match.maxRounds){finishMatch();return;}
 const p=MatchEngine.preview(match);
 if(!p||!p.scene||!Array.isArray(p.atkCards)||!Array.isArray(p.defCards))throw new Error('牌阵数据不完整');
 const pendingMinute=Number.isFinite(p.minute)?p.minute:(Number.isFinite(match.minute)?match.minute:0);$('#sceneInfo').innerHTML=`<b>${pendingMinute}' · ${p.scene?.name||'关键攻防'}</b><br><span class="small">${p.scene?.desc||'局部对抗正在形成'} · ${p.atk||'待定球队'}进攻</span>`;
 $('#duelA').innerHTML=Render.miniBattleCards(p.atk===match.teamA?p.atkCards:p.defCards);
 $('#duelB').innerHTML=Render.miniBattleCards(p.atk===match.teamB?p.atkCards:p.defCards);
 const panel=$('#tacticPanel');panel.classList.remove('hidden');setMatchPhase('tactic');
 $('#tacticChoices').innerHTML=Object.entries(MatchEngine.tactics).map(([k,t])=>`<button type="button" onclick="chooseTactic('${k}')"><b>${t.name}</b><span>${t.desc}</span></button>`).join('');
 addLog(`🎯 ${p.minute}' 已生成${p.scene.name}，请进行战术选择。`);
 
 try{navigator.vibrate&&navigator.vibrate(20)}catch(_){ }
}
function chooseTactic(k){dismissMatchEvent();if(!match||!match.pending)return;setMatchPhase('resolving');setRoundButtonState(false,'生成下一回合');Missions.add(save,'tactics',1);let r=MatchEngine.resolve(match,k);$('#tacticPanel').classList.add('hidden');renderRound(r);setMatchPhase(match.round>=match.maxRounds?'finished':'ready');persist();if(match.round>=match.maxRounds)setTimeout(finishMatch,250)}
function renderRound(r){
 const atkTeam=r.atkTeam||r.attackTeam||r.attackingTeam||'';
 const defTeam=r.defTeam||r.defendingTeam||'';
 const leftAtk=atkTeam===match.teamA;
 const leftData=leftAtk?r.atk:r.def,rightData=leftAtk?r.def:r.atk;
 const leftCards=leftAtk?r.atkCards:r.defCards,rightCards=leftAtk?r.defCards:r.atkCards;
 const atkExtra=`${r.atk.skill?`<div class="skill-banner">✦ 球星技能：${r.atk.skill}</div>`:''}${r.atk.combo?`<div class="combo-banner">⚡ 组合协同 +${r.atk.combo}<small>已计入进攻质量</small></div>`:''}`;
 $('#duelA').innerHTML=`<div class="side-title">${match.teamA} · 本回合${leftAtk?'进攻':'防守'}质量 · ${Math.round(leftData.value)}</div>${leftAtk?atkExtra:''}${Render.miniBattleCards(leftCards)}`;
 $('#duelB').innerHTML=`<div class="side-title">${match.teamB} · 本回合${leftAtk?'防守':'进攻'}质量 · ${Math.round(rightData.value)}</div>${leftAtk?'':atkExtra}${Render.miniBattleCards(rightCards)}`;
 let late=r.minute>=85,leadingAfter=r.goal&&((atkTeam===match.teamA&&match.scoreA>match.scoreB)||(atkTeam===match.teamB&&match.scoreB>match.scoreA));
 let winner=late&&leadingAfter;let event=r.goal?`${winner?'🔥 绝杀！':'⚽'} ${r.scorer.name}进球！`:r.counter?`⚡ 反击得分：${r.scorer.name}`:r.shot?`🧤 门将神扑化解射门`:`⛔ 防线完成解围`;let mode=BetaRelease.config.probabilityMode,details=r.explain.map(x=>`<span>${x}</span>`).join('');$('#probExplain').innerHTML=mode==='full'?`<b>为什么：</b>${details}<strong>形成射门 ${(r.shotProb*100).toFixed(1)}%</strong>`:mode==='expand'?`<b>机会等级：</b><strong>${Math.round(r.shotProb*100)}%</strong><details><summary>展开原因</summary>${details}</details>`:`<b>形成射门机会：</b><strong>${Math.round(r.shotProb*100)}%</strong><span>${r.diff>10?'进攻占优':r.diff<-10?'防守占优':'势均力敌'}</span><small class="decision-help">判断方法：机会越高越适合继续进攻；进攻/防守质量是本回合综合值，组合协同已计入其中，并非额外再加一次。</small>`;if(r.assist&&(r.goal||r.counter))addLog(`↳ 助攻：${r.assist.name}`,'combo');if(r.cardEvent)addLog(`${r.cardEvent.type==='red'?'🟥':'🟨'} ${r.minute}' ${r.cardEvent.player.name} ${r.cardEvent.type==='red'?'红牌':'黄牌'}`);if(r.counterChain)addLog(`🧪 P0-C反击链：夺回球权 → 快速转换 → ${r.counterChain.shot?'形成射门':'被阻断'}${r.counterChain.goal?' → 进球':''}`,'combo');renderLiveEventStats();if(r.aiTactic)addLog(`🤖 AI局势响应：${r.aiTactic.name}`);BetaTools.log(save,'round',{minute:r.minute,scene:r.scene.id,tactic:r.tactic.name,diff:r.diff,shotProb:r.shotProb,saveProb:r.saveProb,goal:r.goal,cardsA:r.atkCards.length,cardsB:r.defCards.length,skill:r.atk.skill,combo:r.atk.combo});addLog(`${r.minute}' ${r.scene.name}｜${r.tactic.name}｜${event}`,r.goal?'goal':r.shot?'save':r.atk.combo?'combo':'normal');showMatchEvent(r,winner);if(window.V18Experience)V18Experience.renderResult(r,match);updateScore()}
function addLog(s,type='normal'){let d=document.createElement('div');d.textContent=s;if(type!=='normal')d.classList.add('timeline-'+type);$('#matchLog').prepend(d)}
function updateScore(){if(!match)return;MatchDirector&&MatchDirector.render(match);$('#scoreNameA').textContent=match.teamA;$('#scoreNameB').textContent=match.teamB;$('#scoreA').textContent=match.scoreA;$('#scoreB').textContent=match.scoreB;$('#round').textContent=match.round;$('#maxRound').textContent=match.maxRounds;$('#minute').textContent=window.V18Experience?V18Experience.clockLabel(match):(match.minute||0)+"'";const v18c=$('#v18Clock'),v18p=$('#v18Phase');if(v18c)v18c.textContent=window.V18Experience?V18Experience.clockLabel(match):(match.minute||0)+"'";if(v18p)v18p.textContent=window.V18Experience?V18Experience.phaseLabel(match):'';$('#moraleA').textContent=Math.round(match.moraleA);$('#moraleB').textContent=Math.round(match.moraleB);$('#matchMode').textContent=match.mode;$('#matchDifficulty').textContent=diffNames[match.difficulty];$('#fitnessA').innerHTML=fitnessSummary(match.teamA);$('#fitnessB').innerHTML=fitnessSummary(match.teamB)}
function dismissMatchEvent(){
 const overlay=$('#eventOverlay'),pitch=$('#matchPitch');
 clearTimeout(window.__eventTimer);window.__eventExpiresAt=0;
 if(window.__eventRaf)cancelAnimationFrame(window.__eventRaf);window.__eventRaf=0;
 if(overlay){overlay.className='event-overlay';overlay.setAttribute('aria-hidden','true');overlay.removeAttribute('style');overlay.innerHTML='';}
 if(pitch)pitch.classList.remove('event-goal','event-save','event-winner');
}
function armMatchEventDismiss(duration){
 const overlay=$('#eventOverlay');if(!overlay)return;
 window.__eventExpiresAt=Date.now()+duration;
 clearTimeout(window.__eventTimer);
 window.__eventTimer=setTimeout(dismissMatchEvent,duration);
 const card=overlay.querySelector('.event-card');
 if(card)card.addEventListener('animationend',e=>{if(e.animationName==='eventAutoDismiss')dismissMatchEvent()},{once:true});
 const tick=()=>{if(!overlay.classList.contains('show'))return;if(Date.now()>=window.__eventExpiresAt){dismissMatchEvent();return}window.__eventRaf=requestAnimationFrame(tick)};
 window.__eventRaf=requestAnimationFrame(tick);
}
function showMatchEvent(r,winner=false){
 const overlay=$('#eventOverlay'),pitch=$('#matchPitch');if(!overlay||!pitch)return;dismissMatchEvent();
 // V1.8继续坚持非阻断表达预算：普通解围和普通扑救只进入实况流，不占据屏幕。
 if(!r.goal&&!r.counter&&!r.atk.combo)return;
 let kind='combo',icon='✨',title='关键协同生效',sub=(r.atk.details||[]).slice(0,2).join('；')||'本回合组合协同已计入进攻质量',extra=comboReasonHtml(r),duration=900;
 if(r.counter){kind='goal';icon='⚡';title='闪电反击';sub=`${r.scorer.name}完成致命一击`;extra='';duration=900;}
 if(r.goal){kind=winner?'winner':'goal';icon=winner?'🔥':'⚽';title=winner?'绝杀进球！':'进球！';sub=`${r.scorer.name} · ${window.V18Experience?V18Experience.clockLabel(match):r.minute+"'"}`;extra='';duration=1000;}
 overlay.className=`event-overlay show auto-dismiss ${kind}`;overlay.setAttribute('aria-hidden','false');overlay.style.setProperty('--event-duration',duration+'ms');overlay.innerHTML=`<div class="event-card" role="status" aria-live="polite"><div class="event-icon">${icon}</div><div class="event-copy"><h2>${title}</h2><p>${sub}</p>${extra}</div></div>`;
 pitch.classList.add(kind==='winner'?'event-winner':kind==='goal'?'event-goal':'');armMatchEventDismiss(duration);
}
function fitnessSummary(team){let ps=Lineup.players(team,save),avg=ps.reduce((s,p)=>s+(match.fitness[p.id]||100),0)/ps.length;return `<span>${team}体能 ${Math.round(avg)}%</span><i style="width:${avg}%"></i>`}

function directorReportHtml(m){const h=(m&&m.directorHistory)||[];if(!h.length)return '';const key=h.slice(-4);const title=key.some(x=>x.key==='desperate')?'背水一战':key.some(x=>x.key==='star')?'球星接管时刻':key.some(x=>x.key==='pressure')?'持续压制':key.some(x=>x.key==='counter')?'攻防转换':key.some(x=>x.key==='block')?'末段控险':'势均力敌';return `<div class="box director-report"><h3>本场走势 · ${title}</h3>${key.map(x=>`<p>${x.minute}′ ${MatchDirector.states[x.key]?.icon||'⚖️'} ${x.name}｜${x.reason}</p>`).join('')}</div>`}
function autoFinish(){if(!match)return startQuick();setMatchPhase('auto');while(match.round<match.maxRounds){if(!match.pending)MatchEngine.preview(match);let r=MatchEngine.resolve(match,'control');renderRound(r)}persist();finishMatch()}
function matchReportHtml(ms){let ev=ms.events||[],goals=ev.filter(x=>x.type==='goal'),cards=ev.filter(x=>x.type==='yellow'||x.type==='red'),story=window.V18Experience?V18Experience.storyHtml(ms):'',timeline=window.V18Experience?V18Experience.timelineHtml(ms):'',integrity=window.V18Experience?V18Experience.integrity(ms):{ok:true,eventCount:0,effectCount:0};return `<div class="post-report"><h3>赛后技术报告</h3><p><b>进球：</b>${goals.length?goals.map(x=>`${x.minute}′ ${x.player}${x.assist?'（助攻 '+x.assist+'）':''}`).join('；'):'无'}</p><p><b>纪律：</b>${cards.length?cards.map(x=>`${x.minute}′ ${x.player} ${x.type==='red'?'🟥':'🟨'}`).join('；'):'无红黄牌'}</p><h3>本场故事</h3>${story}<details><summary>完整V1.8时间轴</summary>${timeline}</details><p class="small">事件一致性：${integrity.ok?'✅ PASS':'❌ FAIL'} · Event ${integrity.eventCount} · Effect ${integrity.effectCount}</p></div>`;}
function finishMatch(){dismissMatchEvent();if(!match||match.finished)return;match.finished=true;setMatchPhase('finished');BetaTools.log(save,'match-finish',{teamA:match.teamA,teamB:match.teamB,scoreA:match.scoreA,scoreB:match.scoreB,rounds:match.round,subsA:match.subsA,subsB:match.subsB});if(match.knockout&&match.scoreA===match.scoreB){let p=MatchEngine.penalties(match.teamA,match.teamB);p.winner===match.teamA?match.scoreA++:match.scoreB++;addLog(`点球大战：${p.winner}晋级`)}Missions.add(save,'matches',1,match.teamA);if(match.scoreA>match.scoreB)Missions.add(save,'wins',1,match.teamA);if((match.mode==='tour-group'||match.mode==='tour-ko')&&tour)Tournament.ingestMatch(tour,match);let res=match.scoreA>match.scoreB?'win':match.scoreA===match.scoreB?'draw':'loss',award=Growth.award(match.teamA,save,res,Object.keys(match.fitness).filter(id=>match.fitness[id]<100)),total=match.stats.possessionA+match.stats.possessionB||1,body=`<div class="statline"><div class="mini">比分<br><b>${match.scoreA}:${match.scoreB}</b></div><div class="mini">射门<br><b>${match.stats.shotsA}:${match.stats.shotsB}</b></div><div class="mini">射正<br><b>${match.stats.onA}:${match.stats.onB}</b></div><div class="mini">控球<br><b>${Math.round(match.stats.possessionA/total*100)}%</b></div></div>${matchReportHtml(match)}${directorReportHtml(match)}<p>金币 +${award.coins}，基础经验 +${award.xp}。成长已继承到下一场。</p>`;Analytics.record(save,match,'control');save.history.unshift({date:new Date().toISOString(),a:match.teamA,b:match.teamB,score:`${match.scoreA}:${match.scoreB}`});save.history=save.history.slice(0,30);save.activeMatch=null;persist();const isTourMatch=match.mode==='tour-group'||match.mode==='tour-ko';postMatchReturnTarget=isTourMatch?'tour':null;Render.modal(res==='win'?'🏆 比赛胜利':res==='draw'?'🤝 平局':'比赛结束',body,isTourMatch?'返回世界杯征程':'确定');if(match.mode==='tour-group')afterTourGroupMatch();if(match.mode==='tour-ko')afterTourKoMatch();renderTrain()}
function openSubModal(){if(!match)return;let team=match.teamA,st=Lineup.players(team,save,'starters'),be=Lineup.players(team,save,'bench');$('#subBody').innerHTML=`<p class="small">已换 ${match.subsA}/5 人。先选择下场球员，再选择替补。</p><select id="subOut">${st.map(p=>`<option value="${p.id}">${p.name} 体能${Math.round(match.fitness[p.id]||100)}%</option>`).join('')}</select><select id="subIn">${be.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select><button class="btn primary full" onclick="confirmSub()">确认换人</button>`;$('#subModal').classList.add('show')}
function confirmSub(){let ok=MatchEngine.substitute(match,match.teamA,$('#subOut').value,$('#subIn').value);if(ok){persist();$('#subModal').classList.remove('show');addLog('🔄 完成换人，新球员体能100%。');updateScore()}else alert('换人失败或已达到5人上限')}
function showPlayer(id){let p=null;Object.values(PLAYER_DATA).forEach((arr)=>{let t=arr.find(x=>id.endsWith('|'+x[0]));if(t){let team=id.split('|')[0];p=Growth.roster(team,save,true).find(x=>x.id===id)}});if(!p){for(let t of Object.values(WORLD_CUP_GROUPS).flat()){p=Growth.roster(t,save,true).find(x=>x.id===id);if(p)break}}if(!p)return;Render.drawRadar(p);$('#playerDetail').innerHTML=`<h2>${p.name} <span class="stage-badge">${Growth.overall(p)}</span></h2><p>${p.team} · ${p.pos} · Lv.${p.level}</p><div class="skills">${(p.skills||[]).map(s=>`<span class="skill">✦ ${s}</span>`).join('')||'团队球员'}</div><p class="small">技能为条件触发：相关场景、关键时间、能力与随机检定共同决定，并受单回合技能加成上限约束。</p>`}
function renderPlayers(){let team=$('#filterTeam').value,teams=$('#detailOnly').checked?Object.keys(PLAYER_DATA):Object.values(WORLD_CUP_GROUPS).flat(),arr=(team&&teams.includes(team)?Growth.roster(team,save,true):teams.flatMap(t=>Growth.roster(t,save,true))).slice(0,220);$('#playerCount').textContent=arr.length;$('#playerGrid').innerHTML=arr.map(p=>Render.playerCard(p,`onclick="showPlayer('${Render.esc(p.id)}')"`)).join('')}
function renderTrain(){let t=$('#quickA').value||'西班牙';$('#upgradeGrid').innerHTML=Growth.roster(t,save,true).slice(0,16).map(p=>`${Render.playerCard(p)}<button class="btn full" onclick="trainPlayer('${Render.esc(p.id)}')">定向训练 120金币</button>`).join('')}
function trainPlayer(id){let r=Growth.train(id,save,$('#trainFocus').value);if(!r.ok)return alert(r.msg);Missions.add(save,'training',1);persist();renderTrain();renderHome();Render.modal('训练完成',`<p>${r.stat}获得提升，球员经验增加。</p>`)}
function wipeSave(){if(confirm('确定清除全部存档？')){Store.wipe();location.reload()}}
function renderTourPreview(){let t=$('#tourTeam').value,g=Object.entries(WORLD_CUP_GROUPS).find(([_,a])=>a.includes(t));$('#tourPreview').innerHTML=g?`<p>${g[0]}组：${g[1].join('、')}</p>`:''}
function startTour(){tour=Tournament.start($('#tourTeam').value);save.tour=tour;persist();renderTournament();Render.modal('世界杯征途已创建',`<p>${tour.team}将从${tour.group}组开始。</p>`)}
function statTable(title,key){let a=Tournament.leaderboard(tour,key);return `<div class="box"><h3>${title}</h3>${a.length?'<div class="leader-list">'+a.map((x,i)=>`<div><b>${i+1}. ${x.name}</b><span>${x.team} · ${x[key]}</span></div>`).join('')+'</div>':'<p class="small">赛事进行后生成。</p>'}</div>`}
function tournamentStoryHtml(t){
 if(!t)return '';
 const reps=(t.matchReports||[]).slice(-5);
 if(!reps.length)return '<div class="box"><h3>本届世界杯故事</h3><p class="small">完成首场比赛后，这里会生成赛事故事摘要。</p></div>';
 let goals=0,cards=0,turning=[];
 reps.forEach(r=>{goals+=(r.scoreA||0)+(r.scoreB||0);cards+=(r.events||[]).filter(e=>e.type==='yellow'||e.type==='red').length;if(r.directorSummary&&r.directorSummary.title)turning.push(r.directorSummary.title)});
 const latest=reps[reps.length-1];
 let title=t.champion?'冠军之路':t.eliminated?'征程回望':t.groupDone?'淘汰赛进行时':'小组赛征途';
 let line=turning.length?turning.slice(-3).join(' · '):`${latest.a} ${latest.scoreA}:${latest.scoreB} ${latest.b}`;
 return `<div class="box tournament-story"><div class="eyebrow">TOURNAMENT STORY</div><h3>${title}</h3><p>${line}</p><div class="statline"><div class="mini">近5场进球<br><b>${goals}</b></div><div class="mini">纪律事件<br><b>${cards}</b></div><div class="mini">当前阶段<br><b>${t.stage}</b></div></div></div>`;
}
function renderTournament(){if(!tour){$('#tourState').innerHTML='<div class="notice">尚未开启征途。</div>';$('#tourStats').innerHTML='';return}Tournament.ensureStats(tour);let next=tour.matchIndex<tour.opponents.length?tour.opponents[tour.matchIndex]:Tournament.nextOpponent(tour);let stateHtml='';if(!tour.groupDone){let rows=Tournament.groupRows(tour,tour.group);stateHtml=`<div class="box"><h2>${tour.team} · ${tour.stage}</h2>${Render.tableHtml(rows)}<p>下一场：${next||'等待赛程'}</p></div>`;}else{let ko=tour.history.filter(h=>h.type==='ko');let status=tour.champion?'🏆 已夺冠':tour.eliminated?'赛事结束':'正在进行淘汰赛';stateHtml=`<div class="box knockout-state"><div class="stage-head"><div><div class="eyebrow">KNOCKOUT STAGE</div><h2>${tour.team} · ${tour.stage}</h2></div><span class="stage-badge">${status}</span></div><div class="knockout-progress">${['32强','16强','8强','半决赛','决赛'].map((x,i)=>`<span class="${i<tour.koIndex?'done':i===tour.koIndex&&!tour.eliminated&&!tour.champion?'current':''}">${x}</span>`).join('')}</div>${ko.length?`<div class="ko-history">${ko.slice(-5).map(h=>`<p><b>${h.stage}</b> · ${h.a} ${h.score} ${h.b} ${h.win?'✅ 晋级':'❌ 出局'}</p>`).join('')}</div>`:'<p class="small">小组积分表已归档，页面已切换为淘汰赛进程。</p>'}<p><b>下一场：</b>${tour.eliminated?'已出局':tour.champion?'已夺冠':next||'等待赛程'}</p></div>`;}$('#tourState').innerHTML=stateHtml;let rep=Tournament.latestReport(tour);$('#tourStats').innerHTML=`${tournamentStoryHtml(tour)}<div class="tour-leaders">${statTable('⚽ 射手榜','goals')}${statTable('🎯 助攻榜','assists')}${statTable('🟨 黄牌榜','yellow')}${statTable('🟥 红牌榜','red')}</div>${rep?`<div class="box"><h3>最近一场赛后报告</h3><p><b>${rep.a} ${rep.scoreA}:${rep.scoreB} ${rep.b}</b> · 射门 ${rep.shotsA}:${rep.shotsB} · 射正 ${rep.onA}:${rep.onB} · 控球 ${rep.posA}%:${100-rep.posA}%</p>${rep.directorSummary?`<p><b>比赛走势：</b>${rep.directorSummary.title}${rep.directorSummary.detail?' · '+rep.directorSummary.detail:''}</p>`:''}${rep.events.filter(x=>x.type==='goal'||x.type==='yellow'||x.type==='red').map(x=>`<p>${x.minute}′ ${x.type==='goal'?'⚽':x.type==='red'?'🟥':'🟨'} ${x.player}${x.assist?' · 助攻 '+x.assist:''}</p>`).join('')}</div>`:''}`}
function tourNext(){if(!tour)return startTour();if(tour.eliminated||tour.champion)return;let opp=!tour.groupDone?tour.opponents[tour.matchIndex]:Tournament.nextOpponent(tour);match=MatchEngine.newState(tour.team,opp,save,{mode:tour.groupDone?'tour-ko':'tour-group',knockout:tour.groupDone,difficulty:'normal'});pendingTournamentOpponent=opp;setMatchPhase('ready');switchTab('match');resetMatchView();updateScore();addLog(`世界杯征途：${tour.team} 对阵 ${opp}`);persist()}
function afterTourGroupMatch(){Tournament.recordUserGroup(tour,pendingTournamentOpponent,match.scoreA,match.scoreB);persist();renderTournament()}
function afterTourKoMatch(){Tournament.recordKnockout(tour,pendingTournamentOpponent,match.scoreA>match.scoreB,`${match.scoreA}:${match.scoreB}`);persist();renderTournament()}
function runSimulation(){let n=Number($('#simCount').value),r=Simulation.run(n);$('#simulationResult').innerHTML=`<h2>${n}场模拟结果</h2><div class="statline"><div class="mini">场均进球<br><b>${r.avg}</b></div><div class="mini">平局率<br><b>${r.draw}%</b></div><div class="mini">较强队胜率<br><b>${r.strong}%</b></div><div class="mini">明显爆冷率<br><b>${r.upset}%</b></div></div><p>高频比分：${r.top.map(x=>`${x[0]}（${x[1]}）`).join('、')}</p><p class="small">该结果用于初步平衡观察，不等同于真实世界杯预测。</p>`}
function renderTech(){$('#techStatus').innerHTML=`<p>存档结构版本：${save.schemaVersion}</p><p>随机种子：比赛内可复现式生成</p><p>阵容数据：与比赛引擎分离</p><p>赛事、成长、UI：独立模块</p><p>已知限制：尚未完成真实外部玩家测试与全设备兼容验证。</p>`}
window.showPlayer=showPlayer;window.trainPlayer=trainPlayer;window.selectStarter=selectStarter;window.swapBench=swapBench;window.chooseTactic=chooseTactic;window.confirmSub=confirmSub;

function applyBuildConfig(){const c=window.BUILD_CONFIG;if(!c)return;const hv=$('#headerVersion'),sb=$('#schemaBadge'),bb=$('#buildBadge');if(hv)hv.textContent=`${c.version} · ${c.codename}`;if(sb)sb.textContent=`🛡️ Schema ${c.schema}`;if(bb)bb.textContent=c.version;}

window.addEventListener('load',()=>{applyBuildConfig();init();});
function renderDashboard(){let s=Analytics.summary(save);$('#dashboardCards').innerHTML=`<div class="mini">比赛<br><b>${s.matches}</b></div><div class="mini">胜率<br><b>${s.winRate}%</b></div><div class="mini">场均进球<br><b>${s.avgFor}</b></div><div class="mini">场均失球<br><b>${s.avgAgainst}</b></div><div class="mini">常用阵型<br><b>${s.topFormation}</b></div>`;$('#recentMatches').innerHTML=(save.history||[]).slice(0,8).map(x=>`<p>${new Date(x.date).toLocaleDateString()} · ${x.a} ${x.score} ${x.b}</p>`).join('')||'<p class="small">暂无比赛记录。</p>';$('#sprintStatus').innerHTML='<p>✅ Sprint 1核心稳定性完整保留</p><p>✅ 1v1、2v2、3v3差异化牌阵布局</p><p>✅ 进球、神扑、解围与绝杀分级演出</p><p>✅ 球星技能与组合技能独立标识</p><p>✅ 关键事件时间轴</p>'}
function generateCoach(){let r=CoachEngine.report(save,$('#coachTeam').value);save.coachReports.unshift(r);save.coachReports=save.coachReports.slice(0,10);persist();$('#coachReport').innerHTML=`<h2>${r.team}教练报告</h2><p>当前阵型：${r.formation}｜样本：${r.summary.matches}场｜胜率：${r.summary.winRate}%</p>${r.advice.map(x=>`<div class="notice compact">${x}</div>`).join('')}`}
function runMatrix(){let n=Number($('#matrixCount').value),r=AdvancedSimulation.run({perPair:n});window.lastMatrix=r;let f=AdvancedSimulation.formations,t=AdvancedSimulation.tactics;function table(labels,data,names){return `<table><tr><th>进攻方\\防守方</th>${labels.map(x=>`<th>${names?.[x]||x}</th>`).join('')}</tr>${labels.map(a=>`<tr><th>${names?.[a]||a}</th>${labels.map(b=>`<td>${data[a][b].win}%</td>`).join('')}</tr>`).join('')}</table>`}$('#matrixResult').innerHTML=`<h3>阵型胜率矩阵</h3>${table(f,r.formations)}<h3>战术胜率矩阵</h3>${table(t,r.tactics,r.tacticNames)}<p class="small">每个格子模拟${n}场，仅用于Sprint 1技术验证。</p>`}

function renderMissions(){Missions.ensure(save);function block(type,id){let list=Missions.list(save,type);$('#'+id).innerHTML=list.map(m=>`<div class="mission-row"><div><b>${m.title}</b><span>${m.progress}/${m.goal} · 奖励${m.reward}金币</span></div><button class="btn ${m.claimed?'':'primary'}" ${m.claimed?'disabled':''} onclick="claimMission('${m.id}')">${m.claimed?'已领取':'领取'}</button></div>`).join('')}block('daily','dailyMissions');block('weekly','weeklyMissions');let e=Economy.report(save);$('#economyReport').innerHTML=`<div class="statline"><div class="mini">余额<br><b>${e.coins}</b></div><div class="mini">累计收入<br><b>${e.income}</b></div><div class="mini">累计消耗<br><b>${e.spend}</b></div><div class="mini">净流入<br><b>${e.net}</b></div></div><p class="small">目标：免费玩家约2场比赛可承担一次基础训练；核心玩法与组合技能全部免费。</p>`}
function claimMission(id){let r=Missions.claim(save,id);if(!r.ok)return alert(r.msg);persist();renderMissions();Render.modal('任务奖励',`<p>获得${r.reward}金币。</p>`)}
function renderShop(){let ok=Shop.integrity();$('#shopIntegrity').innerHTML=`<h2>公平隔离检查：${ok?'✅ 通过':'❌ 未通过'}</h2><p>商品配置不含能力、胜率、技能概率或必胜效果。已记录兴趣 ${(save.shopPrefs||[]).length} 项。</p>`;$('#shopGrid').innerHTML=SHOP_ITEMS.map(x=>`<div class="card shop-card"><div class="rarity">${x.category}</div><h3>${x.name}</h3><p>${x.desc}</p><b>${x.priceLabel}</b><button class="btn full" onclick="shopInterest('${x.id}')">我感兴趣（不购买）</button></div>`).join('')}
function shopInterest(id){let x=Shop.interest(save,id);persist();renderShop();Render.modal('偏好已记录',`<p>${x.name}仅为模拟商品，没有产生交易。</p>`)}
function renderFeedback(){let d=save.feedbackDraft||{};$('#fbRating').value=d.rating||'5';$('#fbFavorite').value=d.favorite||'';$('#fbConfusing').value=d.confusing||'';$('#fbSuggestion').value=d.suggestion||'';$('#fbBusiness').value=d.business||'一次性买断';$('#fbFairness').value=d.fairness||'没有影响'}
function saveFeedback(){Feedback.saveDraft(save,{rating:$('#fbRating').value,favorite:$('#fbFavorite').value,confusing:$('#fbConfusing').value,suggestion:$('#fbSuggestion').value,business:$('#fbBusiness').value,fairness:$('#fbFairness').value});persist();$('#feedbackStatus').textContent='已保存到本机：'+new Date().toLocaleString()}
async function copyFeedback(){saveFeedback();let t=Feedback.text(save);try{await navigator.clipboard.writeText(t);$('#feedbackStatus').textContent='反馈文本已复制。'}catch(e){$('#feedbackStatus').textContent=t}}
window.claimMission=claimMission;window.shopInterest=shopInterest;


// ===== V1.4 Sprint 1: 核心体验与稳定性 =====
const MATCH_PHASE_TEXT={idle:'等待开赛',ready:'可以生成回合',generating:'正在生成牌阵',tactic:'等待选择战术',resolving:'正在结算',auto:'智能托管中',finished:'比赛已结束',error:'发生错误，可重试'};
function setMatchPhase(phase){save.uiState=save.uiState||{};save.uiState.matchPhase=phase;const el=$('#matchPhase');if(el){el.dataset.phase=phase;el.textContent=MATCH_PHASE_TEXT[phase]||phase}}
function updateRecoveryUI(){const bar=$('#recoveryBar'),txt=$('#recoveryText');if(!bar||!txt)return;const active=save.activeMatch&&!save.activeMatch.finished;const currentTab=document.querySelector('.panel.active')?.id||save.lastTab;const sameMatch=!!(match&&save.activeMatch&&match.id&&save.activeMatch.id&&match.id===save.activeMatch.id);const shouldShow=active&&currentTab!=='match'&&!sameMatch;bar.classList.toggle('hidden',!shouldShow);if(shouldShow)txt.textContent=`检测到未结束比赛：${save.activeMatch.teamA} ${save.activeMatch.scoreA||0}:${save.activeMatch.scoreB||0} ${save.activeMatch.teamB} · 第${save.activeMatch.round||0}回合`;}
function restoreActiveMatch(){if(!save.activeMatch||save.activeMatch.finished){updateRecoveryUI();return}try{match=save.activeMatch;if(window.V18Experience)V18Experience.ensureMatch(match);if(match.pending)match.pending=null;setMatchPhase('ready');updateRecoveryUI();}catch(err){save.activeMatch=null;recordRuntimeError(err,'restore-active-match');persist()}}
function continueRecoveredMatch(){if(!match&&save.activeMatch)restoreActiveMatch();if(!match)return Render.modal('没有恢复点','<p>当前没有未结束比赛。</p>');switchTab('match');resetMatchView();updateScore();addLog(`♻️ 已恢复比赛：${match.teamA} 对阵 ${match.teamB}，从第${match.round||0}回合继续。`);persist()}
function discardRecoveredMatch(){if(!confirm('确定清除未结束比赛恢复点吗？世界杯赛事总进度不会被删除。'))return;match=null;save.activeMatch=null;setMatchPhase('idle');persist()}
function recordRuntimeError(err,context){try{save.runtimeErrors=save.runtimeErrors||[];save.runtimeErrors.unshift({time:new Date().toISOString(),context,message:String(err&&err.message||err),stack:String(err&&err.stack||'')});save.runtimeErrors=save.runtimeErrors.slice(0,30);Store.save(save)}catch(_){}}
function initV14UX(){
 setMatchPhase(match?'ready':'idle');updateRecoveryUI();
 const cont=$('#continueMatch'),discard=$('#discardMatch'),more=$('#toggleMore');
 if(cont)cont.onclick=continueRecoveredMatch;if(discard)discard.onclick=discardRecoveredMatch;
 if(more)more.onclick=()=>{document.body.classList.toggle('show-advanced');more.textContent=document.body.classList.contains('show-advanced')?'收起高级功能':'更多功能'};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.id==='nextRound'||b.closest('.tactic-grid'))return;const now=Date.now(),last=Number(b.dataset.lastAction||0);if(now-last<350){e.preventDefault();e.stopImmediatePropagation();return}b.dataset.lastAction=String(now)},true);
 window.addEventListener('error',e=>recordRuntimeError(e.error||e.message,'window-error'));
 window.addEventListener('unhandledrejection',e=>recordRuntimeError(e.reason,'unhandled-rejection'));
 document.addEventListener('visibilitychange',()=>{dismissMatchEvent();if(document.hidden)persist()});
 window.addEventListener('pagehide',()=>persist());
 const last=save.lastTab;if(last&&$('#'+last)&&!['match'].includes(last))switchTab(last);
}
window.continueRecoveredMatch=continueRecoveredMatch;window.discardRecoveredMatch=discardRecoveredMatch;
