(function(){
 function q(id){return document.getElementById(id)}
 function renderConfig(){let c=BetaRelease.config;q('testerGroup').value=c.testerGroup;q('probMode').value=c.probabilityMode;q('buildBadge').textContent=c.buildId;q('groupExplain').textContent=(c.groups[c.testerGroup]||c.groups.A).label+'；商城模式：'+c.shopMode+'；所有组比赛数值完全相同。';q('deviceInfo').textContent=JSON.stringify(BetaRelease.device(),null,2)}
 function renderBackups(){BetaTools.ensure(save);q('backupList').innerHTML=(save.backups||[]).map(b=>`<div class="mission-row"><span>${new Date(b.time).toLocaleString()}</span><button class="btn" onclick="restoreBetaBackup('${b.id}')">恢复</button></div>`).join('')||'<p class="small">尚无备份。</p>'}
 function renderBugs(){BetaTools.ensure(save);q('bugList').innerHTML=(save.bugReports||[]).slice(0,10).map(b=>`<div class="bug-item"><b>${b.severity} · ${b.title}</b><span>${b.status} · ${new Date(b.time).toLocaleString()}</span></div>`).join('')||'<p class="small">尚无Bug报告。</p>'}
 function apply(){BetaRelease.saveConfig({testerGroup:q('testerGroup').value,probabilityMode:q('probMode').value});save.betaRelease={...BetaRelease.config};persist();renderConfig();if(typeof renderShop==='function')renderShop()}
 function rehearsal(){let checks=[['版本编号',!!BetaRelease.config.buildId],['本地存档',(()=>{try{localStorage.setItem('__rr','1');localStorage.removeItem('__rr');return true}catch(e){return false}})()],['新手教学',!!window.Tutorial],['比赛引擎',!!window.MatchEngine],['世界杯引擎',!!window.Tournament],['Bug中心',!!window.BetaTools],['备份恢复',typeof BetaTools.backup==='function'],['商城隔离',window.Shop&&Shop.integrity()],['反馈中心',!!window.Feedback]];q('rehearsalResult').innerHTML=checks.map(x=>`<div class="qa-row ${x[1]?'ok':'bad'}">${x[1]?'✅':'❌'} ${x[0]}</div>`).join('');BetaTools.log(save,'release-rehearsal',{passed:checks.every(x=>x[1]),checks});persist()}
 function initRC(){Tutorial.ensure(save);BetaTools.ensure(save);renderConfig();renderBackups();renderBugs();q('applyBetaConfig').onclick=apply;q('restartTutorial').onclick=()=>Tutorial.start(save);q('tutorialNext').onclick=()=>Tutorial.next(save);q('tutorialSkip').onclick=()=>Tutorial.skip(save);q('runReleaseRehearsal').onclick=rehearsal;q('createBackup').onclick=()=>{BetaTools.backup(save);renderBackups();alert('备份已创建')};q('copyDevice').onclick=async()=>{let t=JSON.stringify(BetaRelease.device(),null,2);try{await navigator.clipboard.writeText(t);alert('设备信息已复制')}catch(e){q('deviceInfo').textContent=t}};q('saveBug').onclick=()=>{let title=q('bugTitle').value.trim();if(!title)return alert('请填写Bug标题');BetaTools.report(save,{severity:q('bugSeverity').value,title,steps:q('bugSteps').value,actual:q('bugActual').value,expected:q('bugExpected').value});persist();renderBugs();alert('Bug报告已保存到本机')};if(BetaRelease.config.tutorialEnabled&&!save.tutorial.completed)setTimeout(()=>Tutorial.start(save),500);let oldRenderShop=window.renderShop;if(oldRenderShop)window.renderShop=function(){oldRenderShop();let grid=q('shopGrid');if(BetaRelease.config.shopMode==='hidden'){grid.innerHTML='<div class="notice">本测试组不显示商城。</div>';return}grid.querySelectorAll('.shop-card').forEach((el,i)=>{let item=SHOP_ITEMS[i];if(item&&!BetaRelease.shouldShow(item))el.remove()});};}
 window.restoreBetaBackup=function(id){if(!confirm('恢复后将覆盖当前本机进度，确定吗？'))return;let r=BetaTools.restore(save,id);if(r)location.reload()};
 window.addEventListener('load',initRC);
})();