(function(){
 function check(name,ok,detail,severity='blocker'){return {name,ok:!!ok,detail,severity}}
 function browserChecks(){let out=[];let ls=false;try{localStorage.setItem('__qa','1');ls=localStorage.getItem('__qa')==='1';localStorage.removeItem('__qa')}catch(e){}out.push(check('本地存档',ls,ls?'可读写':'不可用'));let c=document.createElement('canvas');out.push(check('Canvas雷达图',!!c.getContext,!!c.getContext?'支持':'不支持'));out.push(check('文件导出',typeof Blob!=='undefined'&&typeof URL!=='undefined','Blob/URL能力'));out.push(check('触控环境',('ontouchstart'in window)||navigator.maxTouchPoints>=0,'触控检测完成','warning'));return out}
 function moduleChecks(){return BETA_CONFIG.required.modules.map(n=>check('模块 '+n,typeof window[n]!=='undefined',typeof window[n]))}
 function saveChecks(save){let out=[];out.push(check('存档结构版本',save.schemaVersion===BETA_CONFIG.schema,`当前${save.schemaVersion} / 目标${BETA_CONFIG.schema}`));out.push(check('金币非负',Number.isFinite(save.coins)&&save.coins>=0,`金币${save.coins}`));out.push(check('历史记录结构',Array.isArray(save.history),'history数组'));out.push(check('商城偏好不含能力字段',(save.shopPrefs||[]).every(x=>typeof x==='string'||(x&&!('stats'in x)&&!('boost'in x))),`记录${(save.shopPrefs||[]).length}项`));return out}
 function tournamentChecks(){let out=[];try{let teams=Object.values(WORLD_CUP_GROUPS).flat();out.push(check('世界杯球队数',teams.length===48,`当前${teams.length}队`));out.push(check('世界杯分组数',Object.keys(WORLD_CUP_GROUPS).length===12,`当前${Object.keys(WORLD_CUP_GROUPS).length}组`));out.push(check('分组唯一性',new Set(teams).size===48,`唯一球队${new Set(teams).size}`));}catch(e){out.push(check('世界杯数据',false,e.message))}return out}
 function shopChecks(){let out=[];let items=window.SHOP_ITEMS||[];out.push(check('商城无真实支付',typeof window.StoreKit==='undefined'&&typeof window.PaymentRequest==='undefined','未集成支付SDK'));out.push(check('商品无战力属性',items.every(x=>!x.stats&&!x.boost&&!x.winRate&&!x.skillRate),`${items.length}件商品已扫描`));out.push(check('商品均为模拟',items.every(x=>x.demo!==false),'无真实交易标记'));return out}
 function quickBalance(perPair=40){let report=AdvancedSimulation.run({perPair});let alerts=[];function scan(kind,matrix){Object.entries(matrix).forEach(([a,row])=>{let avg=Object.values(row).reduce((s,x)=>s+x.win,0)/Object.values(row).length;if(avg>BETA_CONFIG.balance.formationHigh||avg<BETA_CONFIG.balance.formationLow)alerts.push({kind,name:a,avg:+avg.toFixed(1),level:'warning'})})}scan('阵型',report.formations);scan('战术',report.tactics);return {report,alerts}}
 function run(save,opts={}){let checks=[...browserChecks(),...moduleChecks(),...saveChecks(save),...tournamentChecks(),...shopChecks()];let bal=null;try{bal=quickBalance(opts.perPair||30);checks.push(check('快速平衡扫描',bal.alerts.length<=4,`预警${bal.alerts.length}项`,'warning'))}catch(e){checks.push(check('快速平衡扫描',false,e.message,'warning'))}let blockers=checks.filter(x=>!x.ok&&x.severity==='blocker').length,warnings=checks.filter(x=>!x.ok&&x.severity!=='blocker').length;let result={at:new Date().toISOString(),checks,blockers,warnings,passed:blockers===0,balance:bal};save.betaQA=save.betaQA||{runs:[]};save.betaQA.last=result;save.betaQA.runs=(save.betaQA.runs||[]).concat([{at:result.at,blockers,warnings,passed:result.passed}]).slice(-20);return result}
 window.BetaQA={run};
})();