(function(){
 const $=s=>document.querySelector(s);function table(rows,cols){if(!rows||!rows.length)return '<p class="small">无可用样本。</p>';return `<table><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[1](r)}</td>`).join('')}</tr>`).join('')}</table>`}
 function saveReport(type,data){try{let s=Store.load();s.diagnostics=s.diagnostics||{runs:[]};s.diagnostics.runs.unshift({type,data});s.diagnostics.runs=s.diagnostics.runs.slice(0,20);Store.save(s)}catch(e){console.warn(e)}}
 function runRounds(){let n=Number($('#diagRoundCount').value),r=DiagnosticsEngine.runRoundBatch(n);saveReport('round-batch',r);let alerts=DiagnosticsEngine.contributionAlerts(r);$('#diagRoundResult').innerHTML=`<div class="statline"><div class="mini">样本回合<br><b>${r.count}</b></div><div class="mini">形成射门<br><b>${r.summary.shotRate}%</b></div><div class="mini">回合进球<br><b>${r.summary.goalRate}%</b></div><div class="mini">平均体能<br><b>${r.summary.avgFitness}</b></div></div><h3>战术贡献</h3>${table(r.tactics,[['战术',x=>AdvancedSimulation.tacticNames[x.name]||x.name],['样本',x=>x.count],['平均射门概率',x=>x.shot+'%'],['回合进球率',x=>x.goalRate+'%']])}<h3>阵型贡献</h3>${table(r.formations,[['阵型',x=>x.name],['样本',x=>x.count],['平均射门概率',x=>x.shot+'%'],['回合进球率',x=>x.goalRate+'%']])}<h3>技能与组合</h3>${table(r.skills.slice(0,8),[['技能',x=>x.name],['触发',x=>x.count],['进球率',x=>x.goalRate+'%']])}${table(r.combos.slice(0,8),[['组合',x=>x.name],['触发',x=>x.count],['进球率',x=>x.goalRate+'%']])}<div class="notice compact"><b>自动预警</b>${alerts.map(x=>`<p>${x}</p>`).join('')}</div>`}
 function runSub(){let r=DiagnosticsEngine.runSubstitution(Number($('#diagSubCount').value));saveReport('substitution',r);$('#diagSubResult').innerHTML=`<div class="statline"><div class="mini">样本<br><b>${r.count}</b></div><div class="mini">平均收益<br><b>${r.avgImpact}</b></div><div class="mini">正收益比例<br><b>${r.positive}%</b></div><div class="mini">建议窗口<br><b>${r.bestWindow}</b></div></div><p>45—59分钟：${r.early}｜60—74分钟：${r.middle}｜75分钟后：${r.late}</p><p class="small">此结果是诊断模型，不代表真实球员换人效果。</p>`}
 function runAI(){let r=DiagnosticsEngine.runAI(Number($('#diagAICount').value));saveReport('ai-pattern',r);$('#diagAIResult').innerHTML=`<div class="statline"><div class="mini">AI决策<br><b>${r.count}</b></div><div class="mini">连续重复<br><b>${r.repeatRate}%</b></div><div class="mini">战术变化<br><b>${r.changeRate}%</b></div></div>${table(r.top,[['战术',x=>x.name],['次数',x=>x.count],['占比',x=>x.share+'%']])}<div class="notice compact"><b>行为预警：</b>${r.warning}</div>`}
 function runEconomy(){let r=DiagnosticsEngine.runEconomy(Number($('#diagDays').value));saveReport('economy',r);$('#diagEconomyResult').innerHTML=`<div class="statline"><div class="mini">周期<br><b>${r.days}天</b></div><div class="mini">期末金币<br><b>${r.end}</b></div><div class="mini">最低余额<br><b>${r.min}</b></div><div class="mini">平均余额<br><b>${r.avg}</b></div></div><div class="notice compact"><b>经济预警：</b>${r.warning}</div><div class="sparkline">${r.series.map(x=>`<i style="height:${Math.max(6,Math.min(100,x.coins/r.max*100))}%" title="第${x.day}天：${x.coins}"></i>`).join('')}</div>`}
 function init(){let map=[['runDiagRounds',runRounds],['runDiagSub',runSub],['runDiagAI',runAI],['runDiagEconomy',runEconomy]];map.forEach(([id,fn])=>{let e=$('#'+id);if(e)e.onclick=fn})}
 window.addEventListener('load',init);
})();
