(function(){let g=null,first=null;const $=s=>document.querySelector(s), names=()=>Object.keys(window.PLAYER_DATA||{});function opt(){let e=$('#dtTeam');if(!e)return;e.innerHTML=names().map(x=>`<option>${x}</option>`).join('')}
function save(){try{localStorage.setItem('wccm_dynamic_v16',JSON.stringify({game:g,updated:new Date().toISOString()}))}catch(e){}}
function card(p){return `<div class="dt-card"><b>${p.name}</b><span>${p.pos} · ${p.overall}</span><small>${(p.skills||[]).slice(0,1).join('')||'基础球员'}</small></div>`}
function log(t){let e=$('#dtLog');e.innerHTML=`<div>${t}</div>`+e.innerHTML}
function tactics(target,cb,exclude){target.innerHTML=Object.entries(DynamicTactics.T).filter(([k])=>k!==exclude).map(([k,v])=>`<button class="btn dt-tactic" data-k="${k}">${v.icon}<br><b>${v.name}</b></button>`).join('');target.querySelectorAll('button').forEach(b=>b.onclick=()=>cb(b.dataset.k,b))}
function update(){if(!g)return;$('#dtTeamA').textContent=g.team;$('#dtTeamB').textContent=g.enemy;$('#dtScoreA').textContent=g.playerScore;$('#dtScoreB').textContent=g.aiScore;$('#dtClock').textContent=g.clock+'′';$('#dtCardsA').innerHTML=g.cardsA.map(card).join('');$('#dtCardsB').innerHTML=g.cardsB.map(card).join('');}
function next(){if(!g||g.phase==='finished')return finish();let r=DynamicTactics.prepare(g);update();first=null;$('#dtContinue').classList.add('hidden');$('#dtSecond').classList.add('hidden');if(r.key){$('#dtStatus').innerHTML='<b>⚡ 关键战术时刻：</b>先选择你的初始方案。';$('#dtSignal').textContent='对手尚未暴露明确意图。';tactics($('#dtTactics'),chooseFirst)}else{$('#dtStatus').innerHTML='<b>普通比赛回合：</b>球队按当前倾向自动执行，保留精力给真正关键的决定。';$('#dtSignal').textContent='本回合自动推进。';$('#dtTactics').innerHTML='<button class="btn primary" id="dtAutoResolve">自动结算本回合</button>';$('#dtAutoResolve').onclick=()=>showResult(DynamicTactics.auto(g))}save()}
function chooseFirst(k,b){first=k;$('#dtTactics').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');g.selected=k;g.aiLocked=g.aiLocked||'organize';$('#dtSignal').innerHTML=`<b>👁 对手意图信号：</b> ${g.signal.text}<br><small>信号可能清晰，也可能具有多义性；AI战术已在你变招前锁定。</small>`;$('#dtSecond').classList.remove('hidden');tactics($('#dtSwitches'),k=>showResult(DynamicTactics.resolve(g,first,k)));let keep=document.createElement('button');keep.className='btn primary dt-tactic';keep.innerHTML='✅<br><b>坚持 '+DynamicTactics.T[k].name+'</b>';keep.onclick=()=>showResult(DynamicTactics.resolve(g,first,first));$('#dtSwitches').prepend(keep)}
function showResult(r){update();$('#dtTactics').innerHTML='';$('#dtSecond').classList.add('hidden');$('#dtSignal').innerHTML=`<b>${r.text}</b>`;$('#dtStatus').textContent=`我方：${DynamicTactics.T[r.final].name}｜AI：${DynamicTactics.T[r.ai].name}｜局势修正 ${r.counter>=0?'+':''}${r.counter}｜转换成本 -${r.cost}`;log(`${r.clock}′ ${r.text}<br><small>AI先锁定：${r.lockedBeforePlayer?'是':'否'}；适配 ${r.fitA}:${r.fitB}；质量差 ${r.quality}；射门概率 ${(r.shot*100).toFixed(1)}%</small>`);$('#dtContinue').classList.toggle('hidden',g.phase==='finished');if(g.phase==='finished')finish();save()}
function finish(){if(!g)return;$('#dtContinue').classList.add('hidden');$('#dtTactics').innerHTML='';$('#dtSecond').classList.add('hidden');$('#dtStatus').innerHTML=`<b>比赛结束：${g.team} ${g.playerScore}:${g.aiScore} ${g.enemy}</b>`;let best=g.review.slice().sort((a,b)=>(b.deception-a.deception)+(b.goal-a.goal)+Math.abs(b.counter)-Math.abs(a.counter)).slice(0,3);$('#dtReview').classList.remove('hidden');$('#dtReview').innerHTML=`<h2>比赛复盘 · 三个关键节点</h2><div class="dt-review-grid">${best.map((x,i)=>`<div class="dt-review-item"><b>${x.clock}′ ${i===0?'⭐ 最佳判断':'关键节点'}</b><p>${x.text}</p><small>${DynamicTactics.T[x.final].name} vs ${DynamicTactics.T[x.ai].name}</small></div>`).join('')}</div><p><b>本场建议：</b>${g.history.filter(x=>x.final===x.first).length>g.history.length*.8?'下一场可更主动地利用变招，但不要机械变招。':'继续观察AI对惯用套路的学习，并在关键时刻制造反向选择。'}</p>`;save()}
function start(){g=DynamicTactics.newGame($('#dtTeam').value,$('#dtPersona').value,$('#dtDifficulty').value);$('#dtGame').classList.remove('hidden');$('#dtReview').classList.add('hidden');$('#dtLog').innerHTML='';log('公平审计：AI每回合先锁定战术，再生成意图信号，最后才允许玩家变招。');next()}
function init(){opt();if(!$('#dtStart'))return;$('#dtStart').onclick=start;$('#dtClear').onclick=()=>{localStorage.removeItem('wccm_dynamic_v16');g=null;$('#dtGame').classList.add('hidden');$('#dtReview').classList.add('hidden')};$('#dtContinue').onclick=next;$('#dtWhy').onclick=()=>$('#dtExplain').open=true;$('#dtExit').onclick=()=>{save();$('#dtGame').classList.add('hidden')};}
window.addEventListener('load',init)})();