(function(){
 const T={organize:{name:'耐心组织',icon:'🧩'},press:{name:'高位压迫',icon:'🔥'},counter:{name:'高速反击',icon:'⚡'},deep:{name:'深度防守',icon:'🛡️'}};
 const matrix={organize:{organize:0,press:-8,counter:2,deep:8},press:{organize:8,press:0,counter:-8,deep:1},counter:{organize:1,press:8,counter:0,deep:-8},deep:{organize:-8,press:2,counter:8,deep:0}};
 const costs={organize:{press:3,counter:2,deep:4},press:{organize:4,counter:3,deep:3},counter:{organize:4,press:5,deep:3},deep:{organize:4,press:5,counter:2}};
 const moments=[2,4,6,8,9]; const clocks=[8,17,27,36,45,54,64,73,82,90];
 function rand(s){s.seed=(s.seed*1664525+1013904223)>>>0;return s.seed/4294967296}
 function roster(team){return (window.PLAYER_DATA[team]||[]).map((x,i)=>({id:team+'_'+i,name:x[0],pos:x[1],overall:x[2],stats:x[3],skills:x[4]||[]}));}
 function pick(team,s,n=3){let a=roster(team).map(p=>({p,k:p.overall+rand(s)*16+(p.skills.length?4:0)})).sort((x,y)=>y.k-x.k);return a.slice(0,1+Math.floor(rand(s)*n)).map(x=>x.p)}
 function flex(cards){let v=cards.reduce((z,p)=>z+(p.stats[2]+p.stats[3])/2+(['CM','AM','DM'].includes(p.pos)?8:0),0)/cards.length;return Math.max(0,Math.min(3,Math.round((v-78)/6)))}
 function adapt(cards,key){const w={organize:[0,0,1,.8,0,0],press:[.5,0,0,0,.8,.6],counter:[.9,.6,.4,.5,0,.2],deep:[0,0,0,0,1,.8]}[key];return cards.reduce((z,p)=>z+p.stats.reduce((q,v,i)=>q+v*w[i],0)/w.reduce((a,b)=>a+b,0),0)/cards.length}
 function aiChoice(s){let p={organize:1,press:1,counter:1,deep:1},d=s.persona;if(d==='wall'){p.deep+=2;p.counter+=1;if(s.aiScore>s.playerScore)p.deep+=2}else{p.press+=2;p.counter+=.6;if(s.aiScore<s.playerScore)p.press+=2}if(s.clock>=73&&s.aiScore>s.playerScore)p.deep+=2;if(s.clock>=73&&s.aiScore<s.playerScore)p.press+=2;
  let top=Object.entries(s.memory).sort((a,b)=>b[1]-a[1])[0];if(top&&top[1]>=2){let counterTo={organize:'press',press:'counter',counter:'deep',deep:'organize'}[top[0]];p[counterTo]+=Math.min(3,top[1]*.6)*(s.difficulty==='expert'?1.25:s.difficulty==='rookie'?.55:1)}
  let total=Object.values(p).reduce((a,b)=>a+b,0),r=rand(s)*total;for(let k of Object.keys(p)){r-=p[k];if(r<=0)return k}return 'organize'}
 function signal(s,key){let clear={organize:['对方中场不断靠近接应，出球节奏正在放慢。','对方正在拉开传球角度，试图耐心控制局面。'],press:['对方整体站位向前，前场人数明显增多。','持球区域附近突然出现多人围抢。'],counter:['对方前锋开始寻找身后空间，中场准备第一时间向前。','对方主动让出部分球权，锋线保持纵向距离。'],deep:['对方中卫持续回收，两条防线之间的空间正在缩小。','对方禁区前沿人数增加，边路通道被暂时放出。']}[key];let vague=['对方边后卫站位发生变化，但意图并不完全清楚。','对方中场移动速度加快，可能正在准备改变比赛节奏。','对方阵线出现短暂调整，需要结合此前打法判断。'];let chance=s.difficulty==='rookie'?.78:s.difficulty==='expert'?.48:.62;let type=rand(s)<chance?'clear':'vague';return {type,text:(type==='clear'?clear:vague)[Math.floor(rand(s)*(type==='clear'?clear.length:vague.length))]}}
 function newGame(team,persona,difficulty){let enemies=Object.keys(window.PLAYER_DATA).filter(x=>x!==team),enemy=enemies[Math.floor(Math.random()*enemies.length)];return {team,enemy,persona,difficulty,round:0,clock:0,playerScore:0,aiScore:0,phase:'ready',seed:(Date.now()^Math.floor(Math.random()*1e9))>>>0,memory:{organize:0,press:0,counter:0,deep:0},history:[],highlights:[],review:[],commits:{},selected:null,aiLocked:null,signal:null,cardsA:[],cardsB:[]}}
 function prepare(s){if(s.round>=10)return {finished:true};s.clock=clocks[s.round];s.cardsA=pick(s.team,s);s.cardsB=pick(s.enemy,s);let key=moments.includes(s.round);s.phase=key?'first':'auto';s.aiLocked=aiChoice(s);s.signal=key?signal(s,s.aiLocked):null;return {key}}
 function resolve(s,first,final){let id='r'+s.round;if(s.commits[id])return s.commits[id];let ai=s.aiLocked||aiChoice(s),switching=first&&final!==first,cost=switching?Math.max(0,(costs[first][final]||3)-flex(s.cardsA)):0;let fitA=adapt(s.cardsA,final),fitB=adapt(s.cardsB,ai),counter=matrix[final][ai],noise=(rand(s)*10-5),quality=fitA-fitB+counter-cost+noise;let shot=.16+Math.max(-.08,Math.min(.18,quality*.006)),goal=rand(s)<shot&&(rand(s)>.46);let aiShot=.14+Math.max(-.07,Math.min(.16,-quality*.005)),aiGoal=rand(s)<aiShot&&(rand(s)>.5);
  let deception=false,top=Object.entries(s.memory).sort((a,b)=>b[1]-a[1])[0];if(top&&top[1]>=2&&final!==top[0]&&matrix[final][ai]>0&&quality>0){deception=true;quality+=3;if(rand(s)<.18)goal=true}
  if(goal)s.playerScore++;if(aiGoal)s.aiScore++;s.memory[final]=(s.memory[final]||0)+1;Object.keys(s.memory).forEach(k=>{if(k!==final)s.memory[k]=Math.max(0,s.memory[k]-.18)});
  let text=counter>0?'战术判断取得优势。':counter<0?'对方战术限制了你的计划。':'双方战术没有形成明显克制。';if(deception)text='🧠 战术欺骗成功！对手针对了你的惯用套路，却暴露了新的空间。';if(goal)text+=' ⚽ 进球！';else if(aiGoal)text+=' 对手抓住机会得分。';else text+=' 本回合未形成进球。';
  let rec={id,round:s.round+1,clock:s.clock,first,final,ai,signal:s.signal&&s.signal.type,switching,cost,fitA:+fitA.toFixed(1),fitB:+fitB.toFixed(1),counter,quality:+quality.toFixed(1),shot:+shot.toFixed(3),goal,aiGoal,deception,text,lockedBeforePlayer:true};s.commits[id]=rec;s.history.push(rec);if(deception||goal||aiGoal||Math.abs(counter)>=8)s.review.push(rec);s.round++;s.phase=s.round>=10?'finished':'between';return rec}
 function auto(s){let ai=s.aiLocked||aiChoice(s),choices=Object.keys(T),final=choices.sort((a,b)=>(adapt(s.cardsA,b)+matrix[b][ai])-(adapt(s.cardsA,a)+matrix[a][ai])).pop();return resolve(s,final,final)}
 window.DynamicTactics={T,matrix,costs,newGame,prepare,resolve,auto,roster};
})();