
(function(){
 const idxMap={速度:0,射门:1,传球:2,盘带:3,防守:4,身体:5};
 const attackPos=new Set(['ST','SS','RW','LW','AM']); const midPos=new Set(['CM','DM','AM']); const defPos=new Set(['GK','CB','RB','LB','DM']);
 function weightedStats(p, weights){let total=0,w=0;Object.entries(weights).forEach(([k,v])=>{total+=p.stats[idxMap[k]]*v;w+=v});return total/(w||1)}
 function shuffle(a){return a.map(x=>[Math.random(),x]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
 function chooseCount(scene){let arr=scene.count||[1,2];return arr[Math.floor(Math.random()*arr.length)]}
 function preferBonus(pos, formation){let rule=FORMATION_RULES[formation]||{};let b=0;if(attackPos.has(pos))b+=rule.attack||2;if(midPos.has(pos))b+=rule.mid||2;if(defPos.has(pos))b+=rule.defense||2;return b}
 function chooseCards(team, scene, side, save, usedIds=[], formation){let pool=Growth.starters(team,save);let prefs=side==='atk'?scene.atk:scene.def;let count=chooseCount(scene);let scored=pool.map(p=>{let pref=prefs.includes(p.pos)?22:0;let fresh=usedIds.includes(p.id)?-8:6;let form=preferBonus(p.pos,formation)*2;let star=(Growth.overall(p)-78)*.35;return {p,score:Math.random()*20+pref+fresh+form+star}}).sort((a,b)=>b.score-a.score);let top=scored.slice(0,Math.min(6,scored.length));return shuffle(top).slice(0,count).map(x=>x.p);}
 function skillBonus(player, weights, minute, isLate){let details=[],bonus=0;let skills=player.skills||[];if(!skills.length)return {bonus,details};skills.forEach(skill=>{let def=SKILL_KEYWORDS.find(k=>skill.includes(k.match));let chance=.16+(Growth.overall(player)-84)*.011+(isLate?.05:0);if(def && Math.random()<chance){let relevant=def.prefer.some(k=>weights[k]);let b=def.bonus+(relevant?5:0)+Math.floor(Math.random()*4);bonus+=b;details.push(`${player.name}「${skill}」${def.text}+${b}`);}else if(!def && Math.random()<.12){let b=5+Math.floor(Math.random()*5);bonus+=b;details.push(`${player.name}「${skill}」+${b}`);}});return {bonus,details};}
 function comboBonus(cards, scene, team, ctx){let names=cards.map(p=>p.name);let pos=cards.map(p=>p.pos);let out=[];let bonus=0;COMBOS.forEach(c=>{if(c.scene && !c.scene.includes(scene.id))return;let ok=false;if(!c.generic){ok=(!c.team||c.team===team)&&c.need.every(n=>names.includes(n));}
   else if(c.condition==='twoCB') ok=pos.filter(x=>x==='CB').length>=2;
   else if(c.condition==='gkDefWall') ok=pos.includes('GK')&&pos.some(x=>['CB','RB','LB'].includes(x));
   else if(c.condition==='goldTriangle') ok=pos.some(x=>['AM','CM'].includes(x))&&pos.some(x=>['RW','LW'].includes(x))&&pos.some(x=>['ST','SS'].includes(x));
   else if(c.condition==='crossTriangle') ok=pos.some(x=>['RB','LB'].includes(x))&&pos.some(x=>['RW','LW'].includes(x))&&pos.includes('ST');
   else if(c.condition==='midPress') ok=pos.filter(x=>['DM','CM','AM'].includes(x)).length>=2;
   else if(c.condition==='desperate') ok=ctx && ctx.trailing && pos.filter(x=>['ST','SS','RW','LW','AM'].includes(x)).length>=2;
   else if(c.condition==='captain') ok=ctx && ctx.captainId && cards.some(p=>p.id===ctx.captainId);
   if(ok){bonus+=c.bonus;out.push(`${c.name}：${c.text} +${c.bonus}`);}
 });return {bonus,details:out};}
 function teamValue(cards, scene, side, team, ctx){let weights=side==='atk'?scene.atkWeights:scene.defWeights;let values=cards.map(p=>weightedStats(p,weights)+(Growth.overall(p)-80)*.22).sort((a,b)=>b-a);let coeff=[1,.65,.45];let base=values.reduce((s,v,i)=>s+v*(coeff[i]||.3),0);let skill=cards.map(p=>skillBonus(p,weights,ctx.minute,ctx.minute>=75));let skillB=skill.reduce((s,x)=>s+x.bonus,0);let skillD=skill.flatMap(x=>x.details);let combo=comboBonus(cards,scene,team,ctx);let fatigue=Math.max(0,(ctx.round-10)*1.4)*(cards.length>=3?1.1:0.8);let morale=(ctx.morale-50)*.12;let random=Math.random()*10-5;let final=base+skillB+combo.bonus-fatigue+morale+random;return {value:final,base,skill:skillB,combo:combo.bonus,fatigue,details:[...combo.details,...skillD]};}
 function goalProbability(diff,scene,atkCombo,minute,knockout){let late=minute>=80?.04:0;let ko=knockout?.025:0;return Math.max(.01,Math.min(.50,scene.goalBase*.75+diff*.0068+atkCombo*.0018+late*.55+ko*.60));}
 function playRound(ms){let scene=SCENES[Math.floor(Math.random()*SCENES.length)];let minute=Math.min(90,Math.round((ms.round+1)*90/(ms.maxRounds||BALANCE.rounds)));let strengthA=Growth.strengthOf(ms.teamA)+(ms.scoreA<ms.scoreB?5:0)+(ms.moraleA-50)*.05;let strengthB=Growth.strengthOf(ms.teamB)+(ms.scoreB<ms.scoreA?5:0)+(ms.moraleB-50)*.05;let aAttacks=Math.random() < strengthA/(strengthA+strengthB);let atkTeam=aAttacks?ms.teamA:ms.teamB, defTeam=aAttacks?ms.teamB:ms.teamA;let atkMorale=aAttacks?ms.moraleA:ms.moraleB, defMorale=aAttacks?ms.moraleB:ms.moraleA;let atkCards=chooseCards(atkTeam,scene,'atk',ms.save,ms.used,ms.formations[atkTeam]);let defCards=chooseCards(defTeam,scene,'def',ms.save,ms.used,ms.formations[defTeam]);let ctxA={round:ms.round,minute,morale:atkMorale,trailing:aAttacks?ms.scoreA<ms.scoreB:ms.scoreB<ms.scoreA,captainId:Growth.captain(atkTeam,ms.save).id};let ctxD={round:ms.round,minute,morale:defMorale,trailing:!aAttacks?ms.scoreA<ms.scoreB:ms.scoreB<ms.scoreA,captainId:Growth.captain(defTeam,ms.save).id};let atk=teamValue(atkCards,scene,'atk',atkTeam,ctxA);let def=teamValue(defCards,scene,'def',defTeam,ctxD);let diff=atk.value-def.value;let prob=goalProbability(diff,scene,atk.combo,minute,ms.knockout);let goal=Math.random()<prob;let counter=false;if(!goal && diff<-22 && Math.random() < Math.min(.18, scene.counter*.75 + (-diff-22)*.0045)){counter=true;}
 let scorer=null;if(goal){scorer=atkCards.find(p=>['ST','SS','RW','LW','AM'].includes(p.pos))||atkCards[0]; if(aAttacks)ms.scoreA++; else ms.scoreB++;}
 if(counter){scorer=defCards.find(p=>['ST','SS','RW','LW','AM'].includes(p.pos))||defCards[0]; if(aAttacks)ms.scoreB++; else ms.scoreA++;}
 ms.round++; ms.used.push(...atkCards.map(p=>p.id),...defCards.map(p=>p.id)); if(goal||counter){if(aAttacks){ms.moraleA += goal?8:-7; ms.moraleB += goal?-6:8;}else{ms.moraleB += goal?8:-7; ms.moraleA += goal?-6:8;}}else{ms.moraleA += Math.random()*4-2; ms.moraleB += Math.random()*4-2;}ms.moraleA=Growth.clamp(ms.moraleA,0,100);ms.moraleB=Growth.clamp(ms.moraleB,0,100);
 return {scene,minute,aAttacks,atkTeam,defTeam,atkCards,defCards,atk,def,diff,prob,goal,counter,scorer,scoreA:ms.scoreA,scoreB:ms.scoreB,round:ms.round};}
 function newState(teamA,teamB,save,opts={}){return {teamA,teamB,save,scoreA:0,scoreB:0,round:0,maxRounds:opts.extra?BALANCE.extraRounds:BALANCE.rounds,moraleA:50,moraleB:50,used:[],knockout:!!opts.knockout,formations:{[teamA]:(TEAM_META[teamA]||{}).formation||'4-3-3',[teamB]:(TEAM_META[teamB]||{}).formation||'4-3-3'},finished:false,mode:opts.mode||'quick'};}
 function simulateScore(teamA,teamB){let sA=Growth.strengthOf(teamA),sB=Growth.strengthOf(teamB),d=(sA-sB)/18;function goals(x){let r=Math.random()+Math.random()+Math.random()+x; if(r<.75)return 0;if(r<1.45)return 1;if(r<2.05)return 2;if(r<2.55)return 3;return 4;}return {a:goals(d),b:goals(-d)};}
 function penalties(teamA,teamB){let a=0,b=0,log=[];for(let i=1;i<=5;i++){let pa=.72+(Growth.strengthOf(teamA)-78)*.003;let pb=.72+(Growth.strengthOf(teamB)-78)*.003;let ga=Math.random()<pa,gb=Math.random()<pb;if(ga)a++;if(gb)b++;log.push(`第${i}轮：${teamA}${ga?'进':'失'}，${teamB}${gb?'进':'失'}`);}let k=6;while(a===b&&k<12){let ga=Math.random()<.72,gb=Math.random()<.72;if(ga)a++;if(gb)b++;log.push(`突然死亡第${k-5}轮：${teamA}${ga?'进':'失'}，${teamB}${gb?'进':'失'}`);k++;}return {a,b,winner:a>b?teamA:teamB,log};}
 window.MatchEngine={newState,playRound,simulateScore,penalties};
})();
