(function(){
 const idx={速度:0,射门:1,传球:2,盘带:3,防守:4,身体:5};
 const tactics={
  control:{name:'控球推进',atk:{传球:.12,盘带:.08},fatigue:2,shot:-.015,counter:-.01,desc:'提高传控，降低失误。'},
  direct:{name:'中路直塞',atk:{传球:.10,射门:.10},fatigue:3,shot:.035,counter:.015,desc:'提高射门形成率，但丢球后有风险。'},
  wing:{name:'边路突破',atk:{速度:.12,盘带:.12},fatigue:4,shot:.025,counter:.02,desc:'适合边路场景。'},
  cross:{name:'长传冲吊',atk:{身体:.14,射门:.07},fatigue:3,shot:.03,counter:.025,desc:'适合高中锋和高空球。'},
  counter:{name:'稳守反击',atk:{速度:.11,传球:.06},def:{防守:.08},fatigue:2,shot:.015,counter:-.02,desc:'降低被反击风险。'},
  press:{name:'高位压迫',atk:{防守:.12,速度:.06},fatigue:6,shot:.02,counter:.035,desc:'抢回球权，但体能消耗大。'},
  defend:{name:'收缩防线',def:{防守:.14,身体:.08},fatigue:1,shot:-.03,counter:-.03,desc:'保护领先优势。'},
  allin:{name:'全员压上',atk:{射门:.16,传球:.08,速度:.06},fatigue:7,shot:.07,counter:.08,desc:'最后阶段搏命。'}
 };
 function rng(state){state.seed=(state.seed*1664525+1013904223)>>>0;return state.seed/4294967296}
 function weighted(p,w,fitness=100){let s=0,t=0;Object.entries(w).forEach(([k,v])=>{s+=p.stats[idx[k]]*v;t+=v});return (s/(t||1))*(.72+.28*fitness/100)}
 function chooseCount(scene,r){let a=scene.count||[1,2];return a[Math.floor(r*a.length)]}
 function choose(team,scene,side,ms){let roster=Lineup.players(team,ms.save,'starters');let prefs=side==='atk'?scene.atk:scene.def,count=chooseCount(scene,rng(ms)),starBoost=window.MatchDirector?MatchDirector.starBoost(ms,team):0;return roster.map(p=>({p,score:rng(ms)*22+(prefs.includes(p.pos)?22:0)+(Growth.overall(p)-78)*.35+(ms.fitness[p.id]||100)*.05+((p.skills||[]).length?starBoost:0)})).sort((a,b)=>b.score-a.score).slice(0,count).map(x=>x.p)}
 function combo(cards,scene,team,ctx){let names=cards.map(p=>p.name),pos=cards.map(p=>p.pos),bonus=0,details=[];COMBOS.forEach(c=>{if(c.scene&&!c.scene.includes(scene.id))return;let ok=false;if(!c.generic)ok=(!c.team||c.team===team)&&c.need.every(n=>names.includes(n));else if(c.condition==='twoCB')ok=pos.filter(x=>x==='CB').length>=2;else if(c.condition==='gkDefWall')ok=pos.includes('GK')&&pos.some(x=>['CB','RB','LB'].includes(x));else if(c.condition==='goldTriangle')ok=pos.some(x=>['AM','CM'].includes(x))&&pos.some(x=>['RW','LW'].includes(x))&&pos.some(x=>['ST','SS'].includes(x));else if(c.condition==='crossTriangle')ok=pos.some(x=>['RB','LB'].includes(x))&&pos.some(x=>['RW','LW'].includes(x))&&pos.includes('ST');else if(c.condition==='midPress')ok=pos.filter(x=>['DM','CM','AM'].includes(x)).length>=2;else if(c.condition==='desperate')ok=ctx.trailing&&pos.filter(x=>['ST','SS','RW','LW','AM'].includes(x)).length>=2;else if(c.condition==='captain')ok=cards.some(p=>p.id===ctx.captainId);if(ok){let b=Math.min(18,c.bonus);bonus+=b;details.push(`${c.name}+${b}`)}});return {bonus:Math.min(24,bonus),details}}
 function skill(cards,scene,ms){let bonus=0,details=[];cards.forEach(p=>(p.skills||[]).forEach(s=>{let chance=.10+Math.max(0,Growth.overall(p)-84)*.008+(ms.minute>=75?.04:0);if(rng(ms)<chance){let b=Math.min(12,5+Math.floor(rng(ms)*7));bonus+=b;details.push(`${p.name}「${s}」+${b}`)}}));return {bonus:Math.min(20,bonus),details}}
 function sideValue(cards,scene,side,team,ms,tacticKey){let baseWeights={...(side==='atk'?scene.atkWeights:scene.defWeights)},t=tactics[tacticKey]||tactics.control,mods=side==='atk'?t.atk:t.def;Object.entries(mods||{}).forEach(([k,v])=>baseWeights[k]=(baseWeights[k]||0)+v);let vals=cards.map(p=>weighted(p,baseWeights,ms.fitness[p.id]||100)+(Growth.overall(p)-80)*.2).sort((a,b)=>b-a),coef=[1,.65,.45],base=vals.reduce((s,v,i)=>s+v*(coef[i]||.3),0),sk=skill(cards,scene,ms),ctx={trailing:team===ms.teamA?ms.scoreA<ms.scoreB:ms.scoreB<ms.scoreA,captainId:Lineup.get(team,ms.save).captainId},co=combo(cards,scene,team,ctx),morale=((team===ms.teamA?ms.moraleA:ms.moraleB)-50)*.1,random=rng(ms)*8-4;return {value:base+sk.bonus+co.bonus+morale+random,base,skill:sk.bonus,combo:co.bonus,morale,details:[...co.details,...sk.details]}}
 function preview(ms){if(ms.pending)return ms.pending;let scene=SCENES[Math.floor(rng(ms)*SCENES.length)],strengthA=Growth.strengthOf(ms.teamA),strengthB=Growth.strengthOf(ms.teamB),aAtk=rng(ms)<strengthA/(strengthA+strengthB),atk=aAtk?ms.teamA:ms.teamB,def=aAtk?ms.teamB:ms.teamA;ms.minute=Math.min(90,Math.round((ms.round+1)*90/ms.maxRounds));ms.pending={minute:ms.minute,scene,aAtk,atk,def,atkCards:choose(atk,scene,'atk',ms),defCards:choose(def,scene,'def',ms)};return ms.pending}
 function resolve(ms,tacticKey='control'){let p=preview(ms),aiTeam=p.atk===ms.teamA?ms.teamB:ms.teamA,aiTactic=tacticKey==='allin'?'counter':(window.MatchDirector?MatchDirector.chooseAITactic(ms,aiTeam,()=>rng(ms)):(rng(ms)<.25?'press':'control')),atkTactic=p.atk===ms.teamA?tacticKey:aiTactic,defTactic=p.def===ms.teamA?tacticKey:aiTactic,a=sideValue(p.atkCards,p.scene,'atk',p.atk,ms,atkTactic),d=sideValue(p.defCards,p.scene,'def',p.def,ms,defTactic),diff=a.value-d.value,t=tactics[atkTactic],base=p.scene.goalBase*.62,formation=.01,shotProb=Math.max(.02,Math.min(.62,base+diff*.0055+(t.shot||0)+formation)),shot=rng(ms)<shotProb,gk=p.defCards.find(x=>x.pos==='GK')||Lineup.players(p.def,ms.save,'starters').find(x=>x.pos==='GK'),saveProb=gk?Math.max(.12,Math.min(.78,(gk.stats[4]*.0048)+(gk.stats[5]*.0018)-Math.max(0,diff)*.0015)):0.35,goal=shot&&rng(ms)>saveProb,counter=false;if(!goal&&diff<-20&&rng(ms)<Math.max(.02,p.scene.counter+(t.counter||0)))counter=true;
 let scorer=null,assist=null,counterChain=null;if(goal){scorer=p.atkCards.find(x=>['ST','SS','RW','LW','AM'].includes(x.pos))||p.atkCards[0];assist=p.atkCards.find(x=>x.id!==scorer.id&&['AM','CM','RW','LW','SS'].includes(x.pos))||null;p.atk===ms.teamA?ms.scoreA++:ms.scoreB++;}if(counter){scorer=p.defCards.find(x=>['ST','SS','RW','LW','AM'].includes(x.pos))||p.defCards[0];assist=p.defCards.find(x=>x.id!==scorer.id&&['AM','CM','RW','LW','SS'].includes(x.pos))||null;p.def===ms.teamA?ms.scoreA++:ms.scoreB++;}
 if(ms.experiments&&ms.experiments.counterChain&&tacticKey==='counter'&&!goal&&!counter){let regain=Math.max(.08,Math.min(.42,.16+(d.value-a.value)*.003));if(rng(ms)<regain){let transition=Math.max(.08,Math.min(.48,.18+(p.defCards.some(x=>x.stats[0]>=86)?.08:0)));let chance=Math.max(.04,Math.min(.38,.10+transition+(ms.minute>=70?.04:0)));let chainShot=rng(ms)<chance,chainGoal=chainShot&&rng(ms)>.48;counterChain={regain:true,transition,shotProb:chance,shot:chainShot,goal:chainGoal};if(chainShot){p.def===ms.teamA?ms.stats.shotsA++:ms.stats.shotsB++;}if(chainGoal){scorer=p.defCards.find(x=>['ST','SS','RW','LW','AM'].includes(x.pos))||p.defCards[0];assist=p.defCards.find(x=>x.id!==scorer.id)||null;p.def===ms.teamA?(ms.scoreA++,ms.stats.onA++):(ms.scoreB++,ms.stats.onB++);counter=true;}}}
 let cardEvent=null;if(rng(ms)<.075){let pool=p.defCards.length?p.defCards:p.atkCards,player=pool[Math.floor(rng(ms)*pool.length)],team=p.def;let yellow=rng(ms)<.9;cardEvent={type:yellow?'yellow':'red',player,team};ms.events.push({minute:ms.minute,type:cardEvent.type,team,playerId:player.id,player:player.name});}
 if((goal||counter)&&scorer){let scoringTeam=goal?p.atk:p.def;ms.events.push({minute:ms.minute,type:'goal',team:scoringTeam,playerId:scorer.id,player:scorer.name,assistId:assist&&assist.id,assist:assist&&assist.name,counter:!!counter});}
 [...p.atkCards,...p.defCards].forEach(x=>ms.fitness[x.id]=Math.max(35,(ms.fitness[x.id]||100)-(tactics[tacticKey].fatigue||2)-(p.atkCards.length+p.defCards.length>4?1:0)));
 ms.stats.possessionA+=p.atk===ms.teamA?(tacticKey==='control'?7:5):3;ms.stats.possessionB+=p.atk===ms.teamB?(tacticKey==='control'?7:5):3;if(shot){p.atk===ms.teamA?ms.stats.shotsA++:ms.stats.shotsB++;if(goal){p.atk===ms.teamA?ms.stats.onA++:ms.stats.onB++;}}
 ms.round++;ms.moraleA=Growth.clamp(ms.moraleA+(goal?(p.atk===ms.teamA?7:-5):rng(ms)*2-1),0,100);ms.moraleB=Growth.clamp(ms.moraleB+(goal?(p.atk===ms.teamB?7:-5):rng(ms)*2-1),0,100);ms.pending=null;
 return {...p,atkTeam:p.atk,defTeam:p.def,atk:a,def:d,diff,shotProb,saveProb,shot,goal,counter,scorer,assist,cardEvent,counterChain,tactic:tactics[tacticKey],aiTactic:tactics[aiTactic],directorState:window.MatchDirector?MatchDirector.evaluate(ms):null,scoreA:ms.scoreA,scoreB:ms.scoreB,round:ms.round,minute:ms.minute,explain:[`基础机会 ${(base*100).toFixed(1)}%`,`牌阵差 ${diff.toFixed(1)}`,`战术 ${tactics[tacticKey].name} ${((t.shot||0)*100).toFixed(1)}%`,`技能 +${a.skill}`,`组合 +${a.combo}`,`门将扑救 ${(saveProb*100).toFixed(1)}%`]}}
 function newState(teamA,teamB,save,opts={}){return {teamA,teamB,save,scoreA:0,scoreB:0,round:0,maxRounds:opts.extra?4:15,minute:0,moraleA:50,moraleB:50,fitness:{...Lineup.fitnessInit(teamA,save),...Lineup.fitnessInit(teamB,save)},stats:{possessionA:0,possessionB:0,shotsA:0,shotsB:0,onA:0,onB:0},events:[],experiments:{counterChain:false},seed:(Date.now()^Math.floor(Math.random()*1e9))>>>0,knockout:!!opts.knockout,mode:opts.mode||'quick',difficulty:opts.difficulty||'normal',finished:false,pending:null,subsA:0,subsB:0,directorHistory:[]}}
 function substitute(ms,team,outId,inId){let st=Lineup.get(team,ms.save),oi=st.starters.indexOf(outId),bi=st.bench.indexOf(inId);if(oi<0||bi<0)return false;let limit=team===ms.teamA?ms.subsA:ms.subsB;if(limit>=5)return false;st.starters[oi]=inId;st.bench[bi]=outId;ms.fitness[inId]=100;team===ms.teamA?ms.subsA++:ms.subsB++;return true}
 function simulateScore(a,b){let sa=Growth.strengthOf(a),sb=Growth.strengthOf(b),pa=1.1+(sa-sb)/28,pb=1.1+(sb-sa)/28;function pois(l){let L=Math.exp(-Math.max(.2,l)),k=0,p=1;do{k++;p*=Math.random()}while(p>L);return Math.min(6,k-1)}return {a:pois(pa),b:pois(pb)}}
 function penalties(a,b){let A=0,B=0,log=[];for(let i=1;i<=5||A===B;i++){let ga=Math.random()<.74,gb=Math.random()<.74;if(ga)A++;if(gb)B++;log.push(`第${i}轮：${a}${ga?'进':'失'}，${b}${gb?'进':'失'}`);if(i>10)break}return {a:A,b:B,winner:A>B?a:b,log}}
 window.MatchEngine={tactics,newState,preview,resolve,substitute,simulateScore,penalties};
})();