
(function(){
 window.$=s=>document.querySelector(s); window.$$=s=>[...document.querySelectorAll(s)];
 function esc(s){return String(s).replace(/'/g,"\\'")}
 function playerCard(p,click=''){let o=Growth.overall(p),legend=o>=90?' legend':'';let sim=p.sim?' blue':'';return `<article class="card${legend}${sim}" ${click}><div class="head"><div><div class="name">${p.name}</div><div class="meta">${p.team} · ${p.pos} · Lv.${p.level}${p.sim?' · 模拟卡':''}</div></div><div class="ovr">${o}</div></div><div class="skills">${(p.skills&&p.skills.length?p.skills:['团队球员']).map(x=>`<span class="skill">✦ ${x}</span>`).join('')}</div><div class="bars">${STAT_NAMES.map((x,i)=>`<span class="bar">${x} ${p.stats[i]}</span>`).join('')}</div><div class="xp"><i style="width:${p.xp%100}%"></i></div><div class="small">经验 ${p.xp%100}/100</div></article>`}
 function miniBattleCards(cards, weights){let count=Math.max(1,Math.min(3,cards.length));return `<div class="battle-cards cards-${count}">${cards.map((p,i)=>`<div class="mini-card ${Growth.overall(p)>=90?'star-card':''}" style="--card-index:${i}"><div class="card-role">${p.pos}</div><div class="small">${p.team}</div><div class="name" style="font-size:13px">${p.name}</div><div class="v">${Growth.overall(p)}</div>${p.skills&&p.skills.length?`<div class="mini-skill">✦ ${p.skills[0]}</div>`:''}</div>`).join('')}</div>`}
 function drawRadar(p){let c=$('#radar'),ctx=c.getContext('2d'),cx=230,cy=230,R=170;ctx.clearRect(0,0,460,460);ctx.font='22px sans-serif';ctx.textAlign='center';for(let r=1;r<=5;r++){ctx.beginPath();for(let i=0;i<6;i++){let q=-Math.PI/2+i*Math.PI/3,x=cx+Math.cos(q)*R*r/5,y=cy+Math.sin(q)*R*r/5;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle='#6d9d7c55';ctx.stroke()}for(let i=0;i<6;i++){let q=-Math.PI/2+i*Math.PI/3;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(q)*R,cy+Math.sin(q)*R);ctx.strokeStyle='#6d9d7c55';ctx.stroke();ctx.fillStyle='#e7f4eb';ctx.fillText(STAT_NAMES[i],cx+Math.cos(q)*(R+30),cy+Math.sin(q)*(R+30)+8)}ctx.beginPath();p.stats.forEach((v,i)=>{let q=-Math.PI/2+i*Math.PI/3,x=cx+Math.cos(q)*R*v/100,y=cy+Math.sin(q)*R*v/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='#ffd16655';ctx.fill();ctx.strokeStyle='#ffd166';ctx.lineWidth=5;ctx.stroke();ctx.lineWidth=1;}
 function teamOptions(select, detailedOnly=false){select.innerHTML='';let names=detailedOnly?Object.keys(PLAYER_DATA):Object.values(WORLD_CUP_GROUPS).flat();names.forEach(t=>select.add(new Option(t+(PLAYER_DATA[t]?'':'（球队模拟）'),t)));}
 function tableHtml(rows){return `<table class="table"><thead><tr><th>球队</th><th>赛</th><th>胜</th><th>平</th><th>负</th><th>进</th><th>失</th><th>净</th><th>分</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}. ${r.team}</td><td>${r.P}</td><td>${r.W}</td><td>${r.D}</td><td>${r.L}</td><td>${r.GF}</td><td>${r.GA}</td><td>${r.GD}</td><td><b>${r.PTS}</b></td></tr>`).join('')}</tbody></table>`}
 function modal(title,body,btn='确定'){ $('#resultTitle').innerHTML=title; $('#resultBody').innerHTML=body; $('#closeModal').textContent=btn; $('#modal').classList.add('show'); }
 window.Render={playerCard,miniBattleCards,drawRadar,teamOptions,tableHtml,modal,esc};
})();
