
(function(){
 function blankTable(){let t={};Object.entries(WORLD_CUP_GROUPS).forEach(([g,arr])=>arr.forEach(team=>t[team]={team,group:g,P:0,W:0,D:0,L:0,GF:0,GA:0,GD:0,PTS:0,FP:0,seed:Growth.strengthOf(team)}));return t}
 function record(table,a,b,ga,gb){let A=table[a],B=table[b];A.P++;B.P++;A.GF+=ga;A.GA+=gb;B.GF+=gb;B.GA+=ga;A.GD=A.GF-A.GA;B.GD=B.GF-B.GA;if(ga>gb){A.W++;B.L++;A.PTS+=3}else if(ga<gb){B.W++;A.L++;B.PTS+=3}else{A.D++;B.D++;A.PTS++;B.PTS++}A.FP+=(Math.random()*3|0);B.FP+=(Math.random()*3|0)}
 function rank(list){return list.slice().sort((a,b)=>b.PTS-a.PTS||b.GD-a.GD||b.GF-a.GF||a.FP-b.FP||b.seed-a.seed)}
 function recordSimStats(tour,a,b,ga,gb){let stats=ensureStats(tour);function goals(team,n){let roster=Growth.roster(team,window.save||{},true).filter(p=>['ST','SS','RW','LW','AM','CM'].includes(p.pos));if(!roster.length)return;for(let i=0;i<n;i++){let p=roster[Math.floor(Math.random()*roster.length)],x=stats[p.id]||(stats[p.id]={id:p.id,name:p.name,team,goals:0,assists:0,yellow:0,red:0,apps:0});x.goals++;if(roster.length>1&&Math.random()<.68){let q=roster.filter(z=>z.id!==p.id)[Math.floor(Math.random()*(roster.length-1))],y=stats[q.id]||(stats[q.id]={id:q.id,name:q.name,team,goals:0,assists:0,yellow:0,red:0,apps:0});y.assists++;}}}goals(a,ga);goals(b,gb)}
 function start(team){let group=Object.entries(WORLD_CUP_GROUPS).find(([g,arr])=>arr.includes(team));if(!group)return null;let opponents=group[1].filter(x=>x!==team);return {team,group:group[0],matchIndex:0,opponents,table:blankTable(),groupDone:false,qualified:false,stage:'小组赛',knockoutTeams:[],koIndex:0,eliminated:false,champion:false,history:[],playerStats:{},matchReports:[]};}
 function playAiGroupMatches(tour, userOpponent){let arr=WORLD_CUP_GROUPS[tour.group];let pairs=[];for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++)pairs.push([arr[i],arr[j]]);let user=tour.team;let played=new Set(tour.history.filter(h=>h.group===tour.group).map(h=>[h.a,h.b].sort().join('|')));pairs.forEach(([a,b])=>{let key=[a,b].sort().join('|');if(played.has(key))return;if(a===user||b===user)return;let r=MatchEngine.simulateScore(a,b);record(tour.table,a,b,r.a,r.b);recordSimStats(tour,a,b,r.a,r.b);tour.history.push({type:'sim',group:tour.group,a,b,ga:r.a,gb:r.b});});}
 function recordUserGroup(tour, opp, ga, gb){record(tour.table,tour.team,opp,ga,gb);tour.history.push({type:'user',group:tour.group,a:tour.team,b:opp,ga,gb});playAiGroupMatches(tour,opp);tour.matchIndex++;if(tour.matchIndex>=tour.opponents.length)finishGroups(tour);}
 function simulateOtherGroups(tour){Object.entries(WORLD_CUP_GROUPS).forEach(([g,arr])=>{if(g===tour.group)return;for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){let a=arr[i],b=arr[j];let r=MatchEngine.simulateScore(a,b);record(tour.table,a,b,r.a,r.b);recordSimStats(tour,a,b,r.a,r.b);tour.history.push({type:'sim',group:g,a,b,ga:r.a,gb:r.b});}});}
 function finishGroups(tour){simulateOtherGroups(tour);tour.groupDone=true;let qualifiers=[];let third=[];Object.entries(WORLD_CUP_GROUPS).forEach(([g,arr])=>{let sorted=rank(arr.map(x=>tour.table[x]));qualifiers.push(sorted[0].team,sorted[1].team);third.push(sorted[2]);});third=rank(third);qualifiers.push(...third.slice(0,BALANCE.thirdAdvanced).map(x=>x.team));tour.knockoutTeams=qualifiers.sort((a,b)=>Growth.strengthOf(b)-Growth.strengthOf(a));tour.qualified=tour.knockoutTeams.includes(tour.team);tour.stage=tour.qualified?'32强淘汰赛':'小组出局';tour.eliminated=!tour.qualified;}
 function nextOpponent(tour){if(!tour.qualified||tour.eliminated||tour.champion)return null;let stages=['32强淘汰赛','16强','8强','半决赛','决赛'];tour.stage=stages[tour.koIndex]||'决赛';let pool=tour.knockoutTeams.filter(x=>x!==tour.team);let target=pool[Math.min(pool.length-1,Math.max(0,Math.floor(pool.length*(.35+Math.random()*.5))-tour.koIndex))]||pool[0];return target;}
 function recordKnockout(tour,opp,win,score){tour.history.push({type:'ko',stage:tour.stage,a:tour.team,b:opp,score,win});if(!win){tour.eliminated=true;tour.stage='淘汰出局';return}tour.koIndex++;if(tour.koIndex>=5){tour.champion=true;tour.stage='世界杯冠军';return}tour.stage=['32强淘汰赛','16强','8强','半决赛','决赛'][tour.koIndex];}
 function groupRows(tour, group=tour.group){return rank(WORLD_CUP_GROUPS[group].map(x=>tour.table[x]));}
 function bestThirdRows(tour){let third=[];Object.entries(WORLD_CUP_GROUPS).forEach(([g,arr])=>{third.push(rank(arr.map(x=>tour.table[x]))[2])});return rank(third);}

 function ensureStats(tour){tour.playerStats=tour.playerStats||{};tour.matchReports=tour.matchReports||[];tour.ingestedMatchIds=Array.isArray(tour.ingestedMatchIds)?tour.ingestedMatchIds:[];return tour.playerStats}
 function ingestMatch(tour,ms){let stats=ensureStats(tour);if(!ms||!ms.id)return false;if(tour.ingestedMatchIds.includes(ms.id))return false;tour.ingestedMatchIds.push(ms.id);tour.ingestedMatchIds=tour.ingestedMatchIds.slice(-120);(ms.events||[]).forEach(e=>{if(!e.playerId)return;let x=stats[e.playerId]||(stats[e.playerId]={id:e.playerId,name:e.player,team:e.team,goals:0,assists:0,yellow:0,red:0,apps:0});if(e.type==='goal'){x.goals++;if(e.assistId){let a=stats[e.assistId]||(stats[e.assistId]={id:e.assistId,name:e.assist,team:e.team,goals:0,assists:0,yellow:0,red:0,apps:0});a.assists++;}}if(e.type==='yellow')x.yellow++;if(e.type==='red')x.red++;});let seen=new Set();(ms.events||[]).forEach(e=>e.playerId&&seen.add(e.playerId));seen.forEach(id=>{if(stats[id])stats[id].apps++});let total=ms.stats.possessionA+ms.stats.possessionB||1;tour.matchReports.push({date:new Date().toISOString(),stage:tour.stage,a:ms.teamA,b:ms.teamB,scoreA:ms.scoreA,scoreB:ms.scoreB,shotsA:ms.stats.shotsA,shotsB:ms.stats.shotsB,onA:ms.stats.onA,onB:ms.stats.onB,posA:Math.round(ms.stats.possessionA/total*100),events:(ms.events||[]).slice(),directorSummary:(typeof MatchDirector!=='undefined'&&MatchDirector.summarize)?MatchDirector.summarize(ms):null});tour.matchReports=tour.matchReports.slice(-40);return true}
 function leaderboard(tour,key){let arr=Object.values(ensureStats(tour));return arr.filter(x=>x[key]>0).sort((a,b)=>b[key]-a[key]||b.goals-a.goals||a.name.localeCompare(b.name)).slice(0,10)}
 function latestReport(tour){ensureStats(tour);return tour.matchReports[tour.matchReports.length-1]||null}
 window.Tournament={start,recordUserGroup,recordKnockout,nextOpponent,groupRows,bestThirdRows,rank,ensureStats,ingestMatch,leaderboard,latestReport};
})();
